// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/git/v1/git.proto

package gitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RepoChunk — kawałek jednego pliku z katalogu .git. Strumień grupuje po rel_path;
// eof=true zamyka plik. repo_path identyfikuje repozytorium (katalog projektu).
type RepoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"` // katalog projektu (tożsamość repo, ścieżka z hosta)
	RelPath       string                 `protobuf:"bytes,2,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`    // ścieżka WEWNĄTRZ .git, np. "HEAD" / "objects/pack/x.pack"
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                         // częściowe bajty pliku rel_path
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`                          // ostatni kawałek tego pliku → zapisz i zamknij
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoChunk) Reset() {
	*x = RepoChunk{}
	mi := &file_proto_git_v1_git_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoChunk) ProtoMessage() {}

func (x *RepoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoChunk.ProtoReflect.Descriptor instead.
func (*RepoChunk) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{0}
}

func (x *RepoChunk) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *RepoChunk) GetRelPath() string {
	if x != nil {
		return x.RelPath
	}
	return ""
}

func (x *RepoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RepoChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Files         int32                  `protobuf:"varint,3,opt,name=files,proto3" json:"files,omitempty"`                            // ile plików odebrano
	HeadBranch    string                 `protobuf:"bytes,4,opt,name=head_branch,json=headBranch,proto3" json:"head_branch,omitempty"` // bieżąca gałąź (lub "" przy detached/HEAD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_proto_git_v1_git_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResult) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *UploadResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UploadResult) GetFiles() int32 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *UploadResult) GetHeadBranch() string {
	if x != nil {
		return x.HeadBranch
	}
	return ""
}

type FileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"` // ścieżka absolutna lub względna do repo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	mi := &file_proto_git_v1_git_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfoRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *FileInfoRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type FileInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tracked         bool                   `protobuf:"varint,1,opt,name=tracked,proto3" json:"tracked,omitempty"` // czy plik jest w historii
	LastAuthor      string                 `protobuf:"bytes,2,opt,name=last_author,json=lastAuthor,proto3" json:"last_author,omitempty"`
	LastAuthorEmail string                 `protobuf:"bytes,3,opt,name=last_author_email,json=lastAuthorEmail,proto3" json:"last_author_email,omitempty"`
	LastCommitHash  string                 `protobuf:"bytes,4,opt,name=last_commit_hash,json=lastCommitHash,proto3" json:"last_commit_hash,omitempty"`
	LastCommitTime  int64                  `protobuf:"varint,5,opt,name=last_commit_time,json=lastCommitTime,proto3" json:"last_commit_time,omitempty"` // unix sekundy
	LastMessage     string                 `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileInfoResponse) Reset() {
	*x = FileInfoResponse{}
	mi := &file_proto_git_v1_git_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResponse) ProtoMessage() {}

func (x *FileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResponse.ProtoReflect.Descriptor instead.
func (*FileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfoResponse) GetTracked() bool {
	if x != nil {
		return x.Tracked
	}
	return false
}

func (x *FileInfoResponse) GetLastAuthor() string {
	if x != nil {
		return x.LastAuthor
	}
	return ""
}

func (x *FileInfoResponse) GetLastAuthorEmail() string {
	if x != nil {
		return x.LastAuthorEmail
	}
	return ""
}

func (x *FileInfoResponse) GetLastCommitHash() string {
	if x != nil {
		return x.LastCommitHash
	}
	return ""
}

func (x *FileInfoResponse) GetLastCommitTime() int64 {
	if x != nil {
		return x.LastCommitTime
	}
	return 0
}

func (x *FileInfoResponse) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Base          string                 `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"` // opcjonalne wymuszenie gałęzi bazowej ("" → auto: main/master)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_proto_git_v1_git_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ReviewRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type ChangedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                      // względna do repo
	AbsPath       string                 `protobuf:"bytes,2,opt,name=abs_path,json=absPath,proto3" json:"abs_path,omitempty"` // repo_path + "/" + path
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                  // new | modified | deleted | renamed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedFile) Reset() {
	*x = ChangedFile{}
	mi := &file_proto_git_v1_git_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedFile) ProtoMessage() {}

func (x *ChangedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedFile.ProtoReflect.Descriptor instead.
func (*ChangedFile) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{5}
}

func (x *ChangedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChangedFile) GetAbsPath() string {
	if x != nil {
		return x.AbsPath
	}
	return ""
}

func (x *ChangedFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReviewStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // użyta gałąź bazowa
	Head          string                 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"` // bieżąca gałąź / ref
	Files         []*ChangedFile         `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewStatusResponse) Reset() {
	*x = ReviewStatusResponse{}
	mi := &file_proto_git_v1_git_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewStatusResponse) ProtoMessage() {}

func (x *ReviewStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewStatusResponse.ProtoReflect.Descriptor instead.
func (*ReviewStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewStatusResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *ReviewStatusResponse) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ReviewStatusResponse) GetFiles() []*ChangedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Base          string                 `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDiffRequest) Reset() {
	*x = FileDiffRequest{}
	mi := &file_proto_git_v1_git_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiffRequest) ProtoMessage() {}

func (x *FileDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiffRequest.ProtoReflect.Descriptor instead.
func (*FileDiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{7}
}

func (x *FileDiffRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *FileDiffRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FileDiffRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type FileDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                            // new | modified | deleted | unchanged
	AddedLines    []int32                `protobuf:"varint,2,rep,packed,name=added_lines,json=addedLines,proto3" json:"added_lines,omitempty"`          // linie (1-based, w HEAD) całkiem nowe → zielone
	ModifiedLines []int32                `protobuf:"varint,3,rep,packed,name=modified_lines,json=modifiedLines,proto3" json:"modified_lines,omitempty"` // linie, które zastąpiły poprzednie → żółte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDiffResponse) Reset() {
	*x = FileDiffResponse{}
	mi := &file_proto_git_v1_git_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiffResponse) ProtoMessage() {}

func (x *FileDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_v1_git_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiffResponse.ProtoReflect.Descriptor instead.
func (*FileDiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_git_v1_git_proto_rawDescGZIP(), []int{8}
}

func (x *FileDiffResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileDiffResponse) GetAddedLines() []int32 {
	if x != nil {
		return x.AddedLines
	}
	return nil
}

func (x *FileDiffResponse) GetModifiedLines() []int32 {
	if x != nil {
		return x.ModifiedLines
	}
	return nil
}

var File_proto_git_v1_git_proto protoreflect.FileDescriptor

const file_proto_git_v1_git_proto_rawDesc = "" +
	"\n" +
	"\x16proto/git/v1/git.proto\x12\x06git.v1\"i\n" +
	"\tRepoChunk\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\brel_path\x18\x02 \x01(\tR\arelPath\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"r\n" +
	"\fUploadResult\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05files\x18\x03 \x01(\x05R\x05files\x12\x1f\n" +
	"\vhead_branch\x18\x04 \x01(\tR\n" +
	"headBranch\"B\n" +
	"\x0fFileInfoRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"\xf0\x01\n" +
	"\x10FileInfoResponse\x12\x18\n" +
	"\atracked\x18\x01 \x01(\bR\atracked\x12\x1f\n" +
	"\vlast_author\x18\x02 \x01(\tR\n" +
	"lastAuthor\x12*\n" +
	"\x11last_author_email\x18\x03 \x01(\tR\x0flastAuthorEmail\x12(\n" +
	"\x10last_commit_hash\x18\x04 \x01(\tR\x0elastCommitHash\x12(\n" +
	"\x10last_commit_time\x18\x05 \x01(\x03R\x0elastCommitTime\x12!\n" +
	"\flast_message\x18\x06 \x01(\tR\vlastMessage\"@\n" +
	"\rReviewRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x12\n" +
	"\x04base\x18\x02 \x01(\tR\x04base\"T\n" +
	"\vChangedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\babs_path\x18\x02 \x01(\tR\aabsPath\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"i\n" +
	"\x14ReviewStatusResponse\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x12\n" +
	"\x04head\x18\x02 \x01(\tR\x04head\x12)\n" +
	"\x05files\x18\x03 \x03(\v2\x13.git.v1.ChangedFileR\x05files\"V\n" +
	"\x0fFileDiffRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04base\x18\x03 \x01(\tR\x04base\"r\n" +
	"\x10FileDiffResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vadded_lines\x18\x02 \x03(\x05R\n" +
	"addedLines\x12%\n" +
	"\x0emodified_lines\x18\x03 \x03(\x05R\rmodifiedLines2\x81\x02\n" +
	"\x03Git\x127\n" +
	"\n" +
	"UploadRepo\x12\x11.git.v1.RepoChunk\x1a\x14.git.v1.UploadResult(\x01\x12=\n" +
	"\bFileInfo\x12\x17.git.v1.FileInfoRequest\x1a\x18.git.v1.FileInfoResponse\x12C\n" +
	"\fReviewStatus\x12\x15.git.v1.ReviewRequest\x1a\x1c.git.v1.ReviewStatusResponse\x12=\n" +
	"\bFileDiff\x12\x17.git.v1.FileDiffRequest\x1a\x18.git.v1.FileDiffResponseB7Z5github.com/filipgorny/ai-architect/proto/git/v1;gitv1b\x06proto3"

var (
	file_proto_git_v1_git_proto_rawDescOnce sync.Once
	file_proto_git_v1_git_proto_rawDescData []byte
)

func file_proto_git_v1_git_proto_rawDescGZIP() []byte {
	file_proto_git_v1_git_proto_rawDescOnce.Do(func() {
		file_proto_git_v1_git_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_git_v1_git_proto_rawDesc), len(file_proto_git_v1_git_proto_rawDesc)))
	})
	return file_proto_git_v1_git_proto_rawDescData
}

var file_proto_git_v1_git_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_git_v1_git_proto_goTypes = []any{
	(*RepoChunk)(nil),            // 0: git.v1.RepoChunk
	(*UploadResult)(nil),         // 1: git.v1.UploadResult
	(*FileInfoRequest)(nil),      // 2: git.v1.FileInfoRequest
	(*FileInfoResponse)(nil),     // 3: git.v1.FileInfoResponse
	(*ReviewRequest)(nil),        // 4: git.v1.ReviewRequest
	(*ChangedFile)(nil),          // 5: git.v1.ChangedFile
	(*ReviewStatusResponse)(nil), // 6: git.v1.ReviewStatusResponse
	(*FileDiffRequest)(nil),      // 7: git.v1.FileDiffRequest
	(*FileDiffResponse)(nil),     // 8: git.v1.FileDiffResponse
}
var file_proto_git_v1_git_proto_depIdxs = []int32{
	5, // 0: git.v1.ReviewStatusResponse.files:type_name -> git.v1.ChangedFile
	0, // 1: git.v1.Git.UploadRepo:input_type -> git.v1.RepoChunk
	2, // 2: git.v1.Git.FileInfo:input_type -> git.v1.FileInfoRequest
	4, // 3: git.v1.Git.ReviewStatus:input_type -> git.v1.ReviewRequest
	7, // 4: git.v1.Git.FileDiff:input_type -> git.v1.FileDiffRequest
	1, // 5: git.v1.Git.UploadRepo:output_type -> git.v1.UploadResult
	3, // 6: git.v1.Git.FileInfo:output_type -> git.v1.FileInfoResponse
	6, // 7: git.v1.Git.ReviewStatus:output_type -> git.v1.ReviewStatusResponse
	8, // 8: git.v1.Git.FileDiff:output_type -> git.v1.FileDiffResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_git_v1_git_proto_init() }
func file_proto_git_v1_git_proto_init() {
	if File_proto_git_v1_git_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_git_v1_git_proto_rawDesc), len(file_proto_git_v1_git_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_git_v1_git_proto_goTypes,
		DependencyIndexes: file_proto_git_v1_git_proto_depIdxs,
		MessageInfos:      file_proto_git_v1_git_proto_msgTypes,
	}.Build()
	File_proto_git_v1_git_proto = out.File
	file_proto_git_v1_git_proto_goTypes = nil
	file_proto_git_v1_git_proto_depIdxs = nil
}
