// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/git/v1/git.proto

package gitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Git_UploadRepo_FullMethodName   = "/git.v1.Git/UploadRepo"
	Git_FileInfo_FullMethodName     = "/git.v1.Git/FileInfo"
	Git_ReviewStatus_FullMethodName = "/git.v1.Git/ReviewStatus"
	Git_FileDiff_FullMethodName     = "/git.v1.Git/FileDiff"
)

// GitClient is the client API for Git service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Git to serwis autorstwa i diff-review. Otwarty projekt WYSYŁA zawartość swojego
// katalogu .git (upload strumieniowy), a serwis odpowiada na pytania o autorstwo
// plików oraz różnicę gałęzi (review). Gateway pośredniczy — Electron nie rusza fs.
type GitClient interface {
	// UploadRepo przyjmuje strumień kawałków katalogu .git projektu i zapisuje go
	// u siebie (kopia robocza historii). Po nim FileInfo/Review działają na kopii.
	UploadRepo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RepoChunk, UploadResult], error)
	// FileInfo zwraca autora OSTATNIEGO commitu dotykającego pliku (git log -1).
	FileInfo(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error)
	// ReviewStatus zwraca pliki zmienione na bieżącej gałęzi względem bazowej
	// (main/master przez merge-base) ze statusem new|modified|deleted|renamed.
	ReviewStatus(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewStatusResponse, error)
	// FileDiff zwraca numery linii (w wersji HEAD pliku) dodanych i zmienionych —
	// do podświetlenia tła w edytorze (dodane = zielonkawe, zmienione = żółtawe).
	FileDiff(ctx context.Context, in *FileDiffRequest, opts ...grpc.CallOption) (*FileDiffResponse, error)
}

type gitClient struct {
	cc grpc.ClientConnInterface
}

func NewGitClient(cc grpc.ClientConnInterface) GitClient {
	return &gitClient{cc}
}

func (c *gitClient) UploadRepo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RepoChunk, UploadResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Git_ServiceDesc.Streams[0], Git_UploadRepo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoChunk, UploadResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Git_UploadRepoClient = grpc.ClientStreamingClient[RepoChunk, UploadResult]

func (c *gitClient) FileInfo(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileInfoResponse)
	err := c.cc.Invoke(ctx, Git_FileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitClient) ReviewStatus(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewStatusResponse)
	err := c.cc.Invoke(ctx, Git_ReviewStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitClient) FileDiff(ctx context.Context, in *FileDiffRequest, opts ...grpc.CallOption) (*FileDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDiffResponse)
	err := c.cc.Invoke(ctx, Git_FileDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServer is the server API for Git service.
// All implementations must embed UnimplementedGitServer
// for forward compatibility.
//
// Git to serwis autorstwa i diff-review. Otwarty projekt WYSYŁA zawartość swojego
// katalogu .git (upload strumieniowy), a serwis odpowiada na pytania o autorstwo
// plików oraz różnicę gałęzi (review). Gateway pośredniczy — Electron nie rusza fs.
type GitServer interface {
	// UploadRepo przyjmuje strumień kawałków katalogu .git projektu i zapisuje go
	// u siebie (kopia robocza historii). Po nim FileInfo/Review działają na kopii.
	UploadRepo(grpc.ClientStreamingServer[RepoChunk, UploadResult]) error
	// FileInfo zwraca autora OSTATNIEGO commitu dotykającego pliku (git log -1).
	FileInfo(context.Context, *FileInfoRequest) (*FileInfoResponse, error)
	// ReviewStatus zwraca pliki zmienione na bieżącej gałęzi względem bazowej
	// (main/master przez merge-base) ze statusem new|modified|deleted|renamed.
	ReviewStatus(context.Context, *ReviewRequest) (*ReviewStatusResponse, error)
	// FileDiff zwraca numery linii (w wersji HEAD pliku) dodanych i zmienionych —
	// do podświetlenia tła w edytorze (dodane = zielonkawe, zmienione = żółtawe).
	FileDiff(context.Context, *FileDiffRequest) (*FileDiffResponse, error)
	mustEmbedUnimplementedGitServer()
}

// UnimplementedGitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitServer struct{}

func (UnimplementedGitServer) UploadRepo(grpc.ClientStreamingServer[RepoChunk, UploadResult]) error {
	return status.Error(codes.Unimplemented, "method UploadRepo not implemented")
}
func (UnimplementedGitServer) FileInfo(context.Context, *FileInfoRequest) (*FileInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileInfo not implemented")
}
func (UnimplementedGitServer) ReviewStatus(context.Context, *ReviewRequest) (*ReviewStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewStatus not implemented")
}
func (UnimplementedGitServer) FileDiff(context.Context, *FileDiffRequest) (*FileDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileDiff not implemented")
}
func (UnimplementedGitServer) mustEmbedUnimplementedGitServer() {}
func (UnimplementedGitServer) testEmbeddedByValue()             {}

// UnsafeGitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServer will
// result in compilation errors.
type UnsafeGitServer interface {
	mustEmbedUnimplementedGitServer()
}

func RegisterGitServer(s grpc.ServiceRegistrar, srv GitServer) {
	// If the following call panics, it indicates UnimplementedGitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Git_ServiceDesc, srv)
}

func _Git_UploadRepo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GitServer).UploadRepo(&grpc.GenericServerStream[RepoChunk, UploadResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Git_UploadRepoServer = grpc.ClientStreamingServer[RepoChunk, UploadResult]

func _Git_FileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServer).FileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Git_FileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServer).FileInfo(ctx, req.(*FileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Git_ReviewStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServer).ReviewStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Git_ReviewStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServer).ReviewStatus(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Git_FileDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServer).FileDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Git_FileDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServer).FileDiff(ctx, req.(*FileDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Git_ServiceDesc is the grpc.ServiceDesc for Git service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Git_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "git.v1.Git",
	HandlerType: (*GitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileInfo",
			Handler:    _Git_FileInfo_Handler,
		},
		{
			MethodName: "ReviewStatus",
			Handler:    _Git_ReviewStatus_Handler,
		},
		{
			MethodName: "FileDiff",
			Handler:    _Git_FileDiff_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadRepo",
			Handler:       _Git_UploadRepo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/git/v1/git.proto",
}
