// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: logs/v1/logs.proto

package logsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_logs_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_logs_v1_logs_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`  // unix milliseconds (when the line was produced)
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"` // "info" | "error"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // optional origin, e.g. "lua", "console"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logs_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logs_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEntry) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_logs_v1_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_logs_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 0 → default (last 500)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQuery) Reset() {
	*x = LogQuery{}
	mi := &file_logs_v1_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQuery) ProtoMessage() {}

func (x *LogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQuery.ProtoReflect.Descriptor instead.
func (*LogQuery) Descriptor() ([]byte, []int) {
	return file_logs_v1_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogList) Reset() {
	*x = LogList{}
	mi := &file_logs_v1_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogList) ProtoMessage() {}

func (x *LogList) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogList.ProtoReflect.Descriptor instead.
func (*LogList) Descriptor() ([]byte, []int) {
	return file_logs_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *LogList) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_logs_v1_logs_proto protoreflect.FileDescriptor

const file_logs_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x12logs/v1/logs.proto\x12\alogs.v1\"\a\n" +
	"\x05Empty\"v\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"7\n" +
	"\bLogBatch\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.logs.v1.LogEntryR\aentries\" \n" +
	"\bLogQuery\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"6\n" +
	"\aLogList\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.logs.v1.LogEntryR\aentries2\x8d\x01\n" +
	"\x04Logs\x12+\n" +
	"\x06Append\x12\x11.logs.v1.LogBatch\x1a\x0e.logs.v1.Empty\x12/\n" +
	"\bListLogs\x12\x11.logs.v1.LogQuery\x1a\x10.logs.v1.LogList\x12'\n" +
	"\x05Clear\x12\x0e.logs.v1.Empty\x1a\x0e.logs.v1.EmptyB9Z7github.com/filipgorny/ai-architect/proto/logs/v1;logsv1b\x06proto3"

var (
	file_logs_v1_logs_proto_rawDescOnce sync.Once
	file_logs_v1_logs_proto_rawDescData []byte
)

func file_logs_v1_logs_proto_rawDescGZIP() []byte {
	file_logs_v1_logs_proto_rawDescOnce.Do(func() {
		file_logs_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_v1_logs_proto_rawDesc), len(file_logs_v1_logs_proto_rawDesc)))
	})
	return file_logs_v1_logs_proto_rawDescData
}

var file_logs_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_logs_v1_logs_proto_goTypes = []any{
	(*Empty)(nil),    // 0: logs.v1.Empty
	(*LogEntry)(nil), // 1: logs.v1.LogEntry
	(*LogBatch)(nil), // 2: logs.v1.LogBatch
	(*LogQuery)(nil), // 3: logs.v1.LogQuery
	(*LogList)(nil),  // 4: logs.v1.LogList
}
var file_logs_v1_logs_proto_depIdxs = []int32{
	1, // 0: logs.v1.LogBatch.entries:type_name -> logs.v1.LogEntry
	1, // 1: logs.v1.LogList.entries:type_name -> logs.v1.LogEntry
	2, // 2: logs.v1.Logs.Append:input_type -> logs.v1.LogBatch
	3, // 3: logs.v1.Logs.ListLogs:input_type -> logs.v1.LogQuery
	0, // 4: logs.v1.Logs.Clear:input_type -> logs.v1.Empty
	0, // 5: logs.v1.Logs.Append:output_type -> logs.v1.Empty
	4, // 6: logs.v1.Logs.ListLogs:output_type -> logs.v1.LogList
	0, // 7: logs.v1.Logs.Clear:output_type -> logs.v1.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logs_v1_logs_proto_init() }
func file_logs_v1_logs_proto_init() {
	if File_logs_v1_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_v1_logs_proto_rawDesc), len(file_logs_v1_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_v1_logs_proto_goTypes,
		DependencyIndexes: file_logs_v1_logs_proto_depIdxs,
		MessageInfos:      file_logs_v1_logs_proto_msgTypes,
	}.Build()
	File_logs_v1_logs_proto = out.File
	file_logs_v1_logs_proto_goTypes = nil
	file_logs_v1_logs_proto_depIdxs = nil
}
