// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: filer/v1/filer.proto

package filerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Filer_Read_FullMethodName         = "/filer.v1.Filer/Read"
	Filer_Save_FullMethodName         = "/filer.v1.Filer/Save"
	Filer_Create_FullMethodName       = "/filer.v1.Filer/Create"
	Filer_Mkdir_FullMethodName        = "/filer.v1.Filer/Mkdir"
	Filer_Rename_FullMethodName       = "/filer.v1.Filer/Rename"
	Filer_Move_FullMethodName         = "/filer.v1.Filer/Move"
	Filer_Delete_FullMethodName       = "/filer.v1.Filer/Delete"
	Filer_Resolve_FullMethodName      = "/filer.v1.Filer/Resolve"
	Filer_Home_FullMethodName         = "/filer.v1.Filer/Home"
	Filer_ListDir_FullMethodName      = "/filer.v1.Filer/ListDir"
	Filer_FindProjects_FullMethodName = "/filer.v1.Filer/FindProjects"
	Filer_Conventions_FullMethodName  = "/filer.v1.Filer/Conventions"
)

// FilerClient is the client API for Filer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Filer to serwis zarządzający plikami projektu (jedyne miejsce dotykające fs
// po stronie backendu). Gateway pośredniczy — Electron nie rusza fs.
type FilerClient interface {
	Read(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Content, error)
	Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*Result, error)
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Result, error)
	Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*Result, error)
	Rename(ctx context.Context, in *RenameReq, opts ...grpc.CallOption) (*Result, error)
	Move(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*Result, error)
	Delete(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Result, error)
	Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*Result, error)
	// Przeglądanie dysku i szukanie projektów (działa też w kontenerze z wolumenem).
	Home(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	ListDir(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*DirListing, error)
	FindProjects(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*ProjectList, error)
	// Conventions wykrywa konwencję nazw plików (dash/camel) i rozszerzenie (język)
	// na podstawie plików w katalogu (i jeden poziom wyżej).
	Conventions(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*ConventionInfo, error)
}

type filerClient struct {
	cc grpc.ClientConnInterface
}

func NewFilerClient(cc grpc.ClientConnInterface) FilerClient {
	return &filerClient{cc}
}

func (c *filerClient) Read(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Content, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Content)
	err := c.cc.Invoke(ctx, Filer_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Rename(ctx context.Context, in *RenameReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Move(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Move_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Delete(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Home(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Filer_Home_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) ListDir(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*DirListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirListing)
	err := c.cc.Invoke(ctx, Filer_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) FindProjects(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*ProjectList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectList)
	err := c.cc.Invoke(ctx, Filer_FindProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filerClient) Conventions(ctx context.Context, in *PathReq, opts ...grpc.CallOption) (*ConventionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConventionInfo)
	err := c.cc.Invoke(ctx, Filer_Conventions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilerServer is the server API for Filer service.
// All implementations must embed UnimplementedFilerServer
// for forward compatibility.
//
// Filer to serwis zarządzający plikami projektu (jedyne miejsce dotykające fs
// po stronie backendu). Gateway pośredniczy — Electron nie rusza fs.
type FilerServer interface {
	Read(context.Context, *PathReq) (*Content, error)
	Save(context.Context, *SaveReq) (*Result, error)
	Create(context.Context, *CreateReq) (*Result, error)
	Mkdir(context.Context, *MkdirReq) (*Result, error)
	Rename(context.Context, *RenameReq) (*Result, error)
	Move(context.Context, *MoveReq) (*Result, error)
	Delete(context.Context, *PathReq) (*Result, error)
	Resolve(context.Context, *ResolveReq) (*Result, error)
	// Przeglądanie dysku i szukanie projektów (działa też w kontenerze z wolumenem).
	Home(context.Context, *Empty) (*Result, error)
	ListDir(context.Context, *PathReq) (*DirListing, error)
	FindProjects(context.Context, *PathReq) (*ProjectList, error)
	// Conventions wykrywa konwencję nazw plików (dash/camel) i rozszerzenie (język)
	// na podstawie plików w katalogu (i jeden poziom wyżej).
	Conventions(context.Context, *PathReq) (*ConventionInfo, error)
	mustEmbedUnimplementedFilerServer()
}

// UnimplementedFilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilerServer struct{}

func (UnimplementedFilerServer) Read(context.Context, *PathReq) (*Content, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedFilerServer) Save(context.Context, *SaveReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedFilerServer) Create(context.Context, *CreateReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedFilerServer) Mkdir(context.Context, *MkdirReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedFilerServer) Rename(context.Context, *RenameReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedFilerServer) Move(context.Context, *MoveReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedFilerServer) Delete(context.Context, *PathReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedFilerServer) Resolve(context.Context, *ResolveReq) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedFilerServer) Home(context.Context, *Empty) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method Home not implemented")
}
func (UnimplementedFilerServer) ListDir(context.Context, *PathReq) (*DirListing, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedFilerServer) FindProjects(context.Context, *PathReq) (*ProjectList, error) {
	return nil, status.Error(codes.Unimplemented, "method FindProjects not implemented")
}
func (UnimplementedFilerServer) Conventions(context.Context, *PathReq) (*ConventionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Conventions not implemented")
}
func (UnimplementedFilerServer) mustEmbedUnimplementedFilerServer() {}
func (UnimplementedFilerServer) testEmbeddedByValue()               {}

// UnsafeFilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilerServer will
// result in compilation errors.
type UnsafeFilerServer interface {
	mustEmbedUnimplementedFilerServer()
}

func RegisterFilerServer(s grpc.ServiceRegistrar, srv FilerServer) {
	// If the following call panics, it indicates UnimplementedFilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Filer_ServiceDesc, srv)
}

func _Filer_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Read(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Save(ctx, req.(*SaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Mkdir(ctx, req.(*MkdirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Rename(ctx, req.(*RenameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Move(ctx, req.(*MoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Delete(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Resolve(ctx, req.(*ResolveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Home_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Home(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).ListDir(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_FindProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).FindProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_FindProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).FindProjects(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filer_Conventions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServer).Conventions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filer_Conventions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServer).Conventions(ctx, req.(*PathReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Filer_ServiceDesc is the grpc.ServiceDesc for Filer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Filer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filer.v1.Filer",
	HandlerType: (*FilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Filer_Read_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Filer_Save_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Filer_Create_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _Filer_Mkdir_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Filer_Rename_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _Filer_Move_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Filer_Delete_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _Filer_Resolve_Handler,
		},
		{
			MethodName: "Home",
			Handler:    _Filer_Home_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _Filer_ListDir_Handler,
		},
		{
			MethodName: "FindProjects",
			Handler:    _Filer_FindProjects_Handler,
		},
		{
			MethodName: "Conventions",
			Handler:    _Filer_Conventions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filer/v1/filer.proto",
}
