// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/filer/v1/filer.proto

package filerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // ścieżka zmienionego pliku/folderu
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`     // create | write | remove | rename
	Dir           bool                   `protobuf:"varint,3,opt,name=dir,proto3" json:"dir,omitempty"`  // czy zmiana dotyczy folderu
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{0}
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FileEvent) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

type ConventionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Convention    string                 `protobuf:"bytes,1,opt,name=convention,proto3" json:"convention,omitempty"` // "dash" | "camel"
	Extension     string                 `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`   // np. "ts"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConventionInfo) Reset() {
	*x = ConventionInfo{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConventionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConventionInfo) ProtoMessage() {}

func (x *ConventionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConventionInfo.ProtoReflect.Descriptor instead.
func (*ConventionInfo) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{1}
}

func (x *ConventionInfo) GetConvention() string {
	if x != nil {
		return x.Convention
	}
	return ""
}

func (x *ConventionInfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{2}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Dir           bool                   `protobuf:"varint,3,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entry) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

type DirListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Parent        string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirListing) Reset() {
	*x = DirListing{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirListing) ProtoMessage() {}

func (x *DirListing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirListing.ProtoReflect.Descriptor instead.
func (*DirListing) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{4}
}

func (x *DirListing) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirListing) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DirListing) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ProjectFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // node | go | git | …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectFound) Reset() {
	*x = ProjectFound{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFound) ProtoMessage() {}

func (x *ProjectFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFound.ProtoReflect.Descriptor instead.
func (*ProjectFound) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectFound) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectFound) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProjectFound) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ProjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectFound        `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectList) Reset() {
	*x = ProjectList{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectList) ProtoMessage() {}

func (x *ProjectList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectList.ProtoReflect.Descriptor instead.
func (*ProjectList) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectList) GetProjects() []*ProjectFound {
	if x != nil {
		return x.Projects
	}
	return nil
}

type PathReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathReq) Reset() {
	*x = PathReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathReq) ProtoMessage() {}

func (x *PathReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathReq.ProtoReflect.Descriptor instead.
func (*PathReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{7}
}

func (x *PathReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{8}
}

func (x *Content) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReq) Reset() {
	*x = SaveReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReq) ProtoMessage() {}

func (x *SaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReq.ProtoReflect.Descriptor instead.
func (*SaveReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{10}
}

func (x *SaveReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // gdy puste, filer wstawia szkielet klasy wg rozszerzenia
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{11}
}

func (x *CreateReq) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *CreateReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MkdirReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirReq) Reset() {
	*x = MkdirReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReq) ProtoMessage() {}

func (x *MkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReq.ProtoReflect.Descriptor instead.
func (*MkdirReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{12}
}

func (x *MkdirReq) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *MkdirReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	FileBase      string                 `protobuf:"bytes,2,opt,name=file_base,json=fileBase,proto3" json:"file_base,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	OldName       string                 `protobuf:"bytes,4,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{13}
}

func (x *RenameReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameReq) GetFileBase() string {
	if x != nil {
		return x.FileBase
	}
	return ""
}

func (x *RenameReq) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *RenameReq) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

type MoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	TargetDir     string                 `protobuf:"bytes,2,opt,name=target_dir,json=targetDir,proto3" json:"target_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{14}
}

func (x *MoveReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *MoveReq) GetTargetDir() string {
	if x != nil {
		return x.TargetDir
	}
	return ""
}

type ResolveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Spec          string                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReq) Reset() {
	*x = ResolveReq{}
	mi := &file_proto_filer_v1_filer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReq) ProtoMessage() {}

func (x *ResolveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filer_v1_filer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReq.ProtoReflect.Descriptor instead.
func (*ResolveReq) Descriptor() ([]byte, []int) {
	return file_proto_filer_v1_filer_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ResolveReq) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

var File_proto_filer_v1_filer_proto protoreflect.FileDescriptor

const file_proto_filer_v1_filer_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/filer/v1/filer.proto\x12\bfiler.v1\"A\n" +
	"\tFileEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\bR\x03dir\"N\n" +
	"\x0eConventionInfo\x12\x1e\n" +
	"\n" +
	"convention\x18\x01 \x01(\tR\n" +
	"convention\x12\x1c\n" +
	"\textension\x18\x02 \x01(\tR\textension\"\a\n" +
	"\x05Empty\"A\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\bR\x03dir\"c\n" +
	"\n" +
	"DirListing\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12)\n" +
	"\aentries\x18\x03 \x03(\v2\x0f.filer.v1.EntryR\aentries\"J\n" +
	"\fProjectFound\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"A\n" +
	"\vProjectList\x122\n" +
	"\bprojects\x18\x01 \x03(\v2\x16.filer.v1.ProjectFoundR\bprojects\"\x1d\n" +
	"\aPathReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\aContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\",\n" +
	"\x06Result\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"7\n" +
	"\aSaveReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"_\n" +
	"\tCreateReq\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"0\n" +
	"\bMkdirReq\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"}\n" +
	"\tRenameReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x1b\n" +
	"\tfile_base\x18\x02 \x01(\tR\bfileBase\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\x12\x19\n" +
	"\bold_name\x18\x04 \x01(\tR\aoldName\"C\n" +
	"\aMoveReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x1d\n" +
	"\n" +
	"target_dir\x18\x02 \x01(\tR\ttargetDir\"4\n" +
	"\n" +
	"ResolveReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\tR\x04spec2\x8a\x05\n" +
	"\x05Filer\x12,\n" +
	"\x04Read\x12\x11.filer.v1.PathReq\x1a\x11.filer.v1.Content\x12+\n" +
	"\x04Save\x12\x11.filer.v1.SaveReq\x1a\x10.filer.v1.Result\x12/\n" +
	"\x06Create\x12\x13.filer.v1.CreateReq\x1a\x10.filer.v1.Result\x12-\n" +
	"\x05Mkdir\x12\x12.filer.v1.MkdirReq\x1a\x10.filer.v1.Result\x12/\n" +
	"\x06Rename\x12\x13.filer.v1.RenameReq\x1a\x10.filer.v1.Result\x12+\n" +
	"\x04Move\x12\x11.filer.v1.MoveReq\x1a\x10.filer.v1.Result\x12-\n" +
	"\x06Delete\x12\x11.filer.v1.PathReq\x1a\x10.filer.v1.Result\x121\n" +
	"\aResolve\x12\x14.filer.v1.ResolveReq\x1a\x10.filer.v1.Result\x12)\n" +
	"\x04Home\x12\x0f.filer.v1.Empty\x1a\x10.filer.v1.Result\x122\n" +
	"\aListDir\x12\x11.filer.v1.PathReq\x1a\x14.filer.v1.DirListing\x128\n" +
	"\fFindProjects\x12\x11.filer.v1.PathReq\x1a\x15.filer.v1.ProjectList\x12:\n" +
	"\vConventions\x12\x11.filer.v1.PathReq\x1a\x18.filer.v1.ConventionInfo\x121\n" +
	"\x05Watch\x12\x11.filer.v1.PathReq\x1a\x13.filer.v1.FileEvent0\x01B;Z9github.com/filipgorny/ai-architect/proto/filer/v1;filerv1b\x06proto3"

var (
	file_proto_filer_v1_filer_proto_rawDescOnce sync.Once
	file_proto_filer_v1_filer_proto_rawDescData []byte
)

func file_proto_filer_v1_filer_proto_rawDescGZIP() []byte {
	file_proto_filer_v1_filer_proto_rawDescOnce.Do(func() {
		file_proto_filer_v1_filer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filer_v1_filer_proto_rawDesc), len(file_proto_filer_v1_filer_proto_rawDesc)))
	})
	return file_proto_filer_v1_filer_proto_rawDescData
}

var file_proto_filer_v1_filer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_filer_v1_filer_proto_goTypes = []any{
	(*FileEvent)(nil),      // 0: filer.v1.FileEvent
	(*ConventionInfo)(nil), // 1: filer.v1.ConventionInfo
	(*Empty)(nil),          // 2: filer.v1.Empty
	(*Entry)(nil),          // 3: filer.v1.Entry
	(*DirListing)(nil),     // 4: filer.v1.DirListing
	(*ProjectFound)(nil),   // 5: filer.v1.ProjectFound
	(*ProjectList)(nil),    // 6: filer.v1.ProjectList
	(*PathReq)(nil),        // 7: filer.v1.PathReq
	(*Content)(nil),        // 8: filer.v1.Content
	(*Result)(nil),         // 9: filer.v1.Result
	(*SaveReq)(nil),        // 10: filer.v1.SaveReq
	(*CreateReq)(nil),      // 11: filer.v1.CreateReq
	(*MkdirReq)(nil),       // 12: filer.v1.MkdirReq
	(*RenameReq)(nil),      // 13: filer.v1.RenameReq
	(*MoveReq)(nil),        // 14: filer.v1.MoveReq
	(*ResolveReq)(nil),     // 15: filer.v1.ResolveReq
}
var file_proto_filer_v1_filer_proto_depIdxs = []int32{
	3,  // 0: filer.v1.DirListing.entries:type_name -> filer.v1.Entry
	5,  // 1: filer.v1.ProjectList.projects:type_name -> filer.v1.ProjectFound
	7,  // 2: filer.v1.Filer.Read:input_type -> filer.v1.PathReq
	10, // 3: filer.v1.Filer.Save:input_type -> filer.v1.SaveReq
	11, // 4: filer.v1.Filer.Create:input_type -> filer.v1.CreateReq
	12, // 5: filer.v1.Filer.Mkdir:input_type -> filer.v1.MkdirReq
	13, // 6: filer.v1.Filer.Rename:input_type -> filer.v1.RenameReq
	14, // 7: filer.v1.Filer.Move:input_type -> filer.v1.MoveReq
	7,  // 8: filer.v1.Filer.Delete:input_type -> filer.v1.PathReq
	15, // 9: filer.v1.Filer.Resolve:input_type -> filer.v1.ResolveReq
	2,  // 10: filer.v1.Filer.Home:input_type -> filer.v1.Empty
	7,  // 11: filer.v1.Filer.ListDir:input_type -> filer.v1.PathReq
	7,  // 12: filer.v1.Filer.FindProjects:input_type -> filer.v1.PathReq
	7,  // 13: filer.v1.Filer.Conventions:input_type -> filer.v1.PathReq
	7,  // 14: filer.v1.Filer.Watch:input_type -> filer.v1.PathReq
	8,  // 15: filer.v1.Filer.Read:output_type -> filer.v1.Content
	9,  // 16: filer.v1.Filer.Save:output_type -> filer.v1.Result
	9,  // 17: filer.v1.Filer.Create:output_type -> filer.v1.Result
	9,  // 18: filer.v1.Filer.Mkdir:output_type -> filer.v1.Result
	9,  // 19: filer.v1.Filer.Rename:output_type -> filer.v1.Result
	9,  // 20: filer.v1.Filer.Move:output_type -> filer.v1.Result
	9,  // 21: filer.v1.Filer.Delete:output_type -> filer.v1.Result
	9,  // 22: filer.v1.Filer.Resolve:output_type -> filer.v1.Result
	9,  // 23: filer.v1.Filer.Home:output_type -> filer.v1.Result
	4,  // 24: filer.v1.Filer.ListDir:output_type -> filer.v1.DirListing
	6,  // 25: filer.v1.Filer.FindProjects:output_type -> filer.v1.ProjectList
	1,  // 26: filer.v1.Filer.Conventions:output_type -> filer.v1.ConventionInfo
	0,  // 27: filer.v1.Filer.Watch:output_type -> filer.v1.FileEvent
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_filer_v1_filer_proto_init() }
func file_proto_filer_v1_filer_proto_init() {
	if File_proto_filer_v1_filer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filer_v1_filer_proto_rawDesc), len(file_proto_filer_v1_filer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filer_v1_filer_proto_goTypes,
		DependencyIndexes: file_proto_filer_v1_filer_proto_depIdxs,
		MessageInfos:      file_proto_filer_v1_filer_proto_msgTypes,
	}.Build()
	File_proto_filer_v1_filer_proto = out.File
	file_proto_filer_v1_filer_proto_goTypes = nil
	file_proto_filer_v1_filer_proto_depIdxs = nil
}
