// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ai/v1/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`                   // kontekst: bieżący plik (absolutna ścieżka)
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // kontekst: node
	AppId         int64                  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Edit          bool                   `protobuf:"varint,5,opt,name=edit,proto3" json:"edit,omitempty"` // true = zwróć zmodyfikowany kod pliku
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AskRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *AskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AskRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AskRequest) GetEdit() bool {
	if x != nil {
		return x.Edit
	}
	return false
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // read_file | check_events | list_dir
	Args          string                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AskEvent_Plan
	//	*AskEvent_Tool
	//	*AskEvent_Answer
	Event         isAskEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskEvent) Reset() {
	*x = AskEvent{}
	mi := &file_proto_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskEvent) ProtoMessage() {}

func (x *AskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskEvent.ProtoReflect.Descriptor instead.
func (*AskEvent) Descriptor() ([]byte, []int) {
	return file_proto_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AskEvent) GetEvent() isAskEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AskEvent) GetPlan() string {
	if x != nil {
		if x, ok := x.Event.(*AskEvent_Plan); ok {
			return x.Plan
		}
	}
	return ""
}

func (x *AskEvent) GetTool() *ToolCall {
	if x != nil {
		if x, ok := x.Event.(*AskEvent_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *AskEvent) GetAnswer() string {
	if x != nil {
		if x, ok := x.Event.(*AskEvent_Answer); ok {
			return x.Answer
		}
	}
	return ""
}

type isAskEvent_Event interface {
	isAskEvent_Event()
}

type AskEvent_Plan struct {
	Plan string `protobuf:"bytes,1,opt,name=plan,proto3,oneof"` // plan przed wykonaniem
}

type AskEvent_Tool struct {
	Tool *ToolCall `protobuf:"bytes,2,opt,name=tool,proto3,oneof"` // użyte narzędzie + wynik
}

type AskEvent_Answer struct {
	Answer string `protobuf:"bytes,3,opt,name=answer,proto3,oneof"` // końcowa odpowiedź (lub zmodyfikowany kod)
}

func (*AskEvent_Plan) isAskEvent_Event() {}

func (*AskEvent_Tool) isAskEvent_Event() {}

func (*AskEvent_Answer) isAskEvent_Event() {}

var File_proto_ai_v1_ai_proto protoreflect.FileDescriptor

const file_proto_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ai/v1/ai.proto\x12\x05ai.v1\"\x82\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\"&\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"|\n" +
	"\n" +
	"AskRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04edit\x18\x05 \x01(\bR\x04edit\"J\n" +
	"\bToolCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"j\n" +
	"\bAskEvent\x12\x14\n" +
	"\x04plan\x18\x01 \x01(\tH\x00R\x04plan\x12%\n" +
	"\x04tool\x18\x02 \x01(\v2\x0f.ai.v1.ToolCallH\x00R\x04tool\x12\x18\n" +
	"\x06answer\x18\x03 \x01(\tH\x00R\x06answerB\a\n" +
	"\x05event2n\n" +
	"\x02Ai\x12+\n" +
	"\x03Ask\x12\x11.ai.v1.AskRequest\x1a\x0f.ai.v1.AskEvent0\x01\x12;\n" +
	"\bGenerate\x12\x16.ai.v1.GenerateRequest\x1a\x17.ai.v1.GenerateResponseB5Z3github.com/filipgorny/ai-architect/proto/ai/v1;aiv1b\x06proto3"

var (
	file_proto_ai_v1_ai_proto_rawDescOnce sync.Once
	file_proto_ai_v1_ai_proto_rawDescData []byte
)

func file_proto_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_v1_ai_proto_rawDesc), len(file_proto_ai_v1_ai_proto_rawDesc)))
	})
	return file_proto_ai_v1_ai_proto_rawDescData
}

var file_proto_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ai_v1_ai_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: ai.v1.GenerateRequest
	(*GenerateResponse)(nil), // 1: ai.v1.GenerateResponse
	(*AskRequest)(nil),       // 2: ai.v1.AskRequest
	(*ToolCall)(nil),         // 3: ai.v1.ToolCall
	(*AskEvent)(nil),         // 4: ai.v1.AskEvent
}
var file_proto_ai_v1_ai_proto_depIdxs = []int32{
	3, // 0: ai.v1.AskEvent.tool:type_name -> ai.v1.ToolCall
	2, // 1: ai.v1.Ai.Ask:input_type -> ai.v1.AskRequest
	0, // 2: ai.v1.Ai.Generate:input_type -> ai.v1.GenerateRequest
	4, // 3: ai.v1.Ai.Ask:output_type -> ai.v1.AskEvent
	1, // 4: ai.v1.Ai.Generate:output_type -> ai.v1.GenerateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ai_v1_ai_proto_init() }
func file_proto_ai_v1_ai_proto_init() {
	if File_proto_ai_v1_ai_proto != nil {
		return
	}
	file_proto_ai_v1_ai_proto_msgTypes[4].OneofWrappers = []any{
		(*AskEvent_Plan)(nil),
		(*AskEvent_Tool)(nil),
		(*AskEvent_Answer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_v1_ai_proto_rawDesc), len(file_proto_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_v1_ai_proto = out.File
	file_proto_ai_v1_ai_proto_goTypes = nil
	file_proto_ai_v1_ai_proto_depIdxs = nil
}
