// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ai/v1/ai.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ai_Ask_FullMethodName            = "/ai.v1.Ai/Ask"
	Ai_Generate_FullMethodName       = "/ai.v1.Ai/Generate"
	Ai_Model_FullMethodName          = "/ai.v1.Ai/Model"
	Ai_SetProvider_FullMethodName    = "/ai.v1.Ai/SetProvider"
	Ai_SetClaudeToken_FullMethodName = "/ai.v1.Ai/SetClaudeToken"
	Ai_ClaudeStatus_FullMethodName   = "/ai.v1.Ai/ClaudeStatus"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ai to agent ze skillami (czytanie pliku, sprawdzanie eventów). PLANUJE przed
// wykonaniem, a postęp (plan, użyte narzędzia, odpowiedź) strumieniuje.
type AiClient interface {
	// Ask to agent ze skillami — DWUKIERUNKOWY stream. Aplikacja wysyła start (zadanie +
	// kontekst) oraz odpowiedzi na żądania skilli; serwer strumieniuje plan, użyte narzędzia,
	// żądania skilli (read_file/list_dir/get_graph wykonywane przez aplikację) i odpowiedź.
	Ask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AskClientMsg, AskEvent], error)
	// Generate to proste wywołanie LLM — wszystko inne (np. opis plików w
	// scannerze) idzie przez ten serwis, by LLM był w jednym miejscu.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	// Model zwraca nazwę aktualnie używanego modelu.
	Model(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error)
	// SetProvider podmienia dostawcę LLM w locie (np. ollama → claude headless).
	SetProvider(ctx context.Context, in *SetProviderRequest, opts ...grpc.CallOption) (*ModelResponse, error)
	// SetClaudeToken zapisuje długoterminowy token OAuth (claude setup-token) używany
	// przez `claude -p` w trybie headless. Serwis persystuje go u siebie (wolumen).
	SetClaudeToken(ctx context.Context, in *SetClaudeTokenRequest, opts ...grpc.CallOption) (*ClaudeTokenStatus, error)
	// ClaudeStatus mówi, czy serwis ma zapisany token Claude (do bramki logowania w UI).
	ClaudeStatus(ctx context.Context, in *ClaudeStatusRequest, opts ...grpc.CallOption) (*ClaudeTokenStatus, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) Ask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AskClientMsg, AskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ai_ServiceDesc.Streams[0], Ai_Ask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskClientMsg, AskEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_AskClient = grpc.BidiStreamingClient[AskClientMsg, AskEvent]

func (c *aiClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, Ai_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) Model(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, Ai_Model_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) SetProvider(ctx context.Context, in *SetProviderRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, Ai_SetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) SetClaudeToken(ctx context.Context, in *SetClaudeTokenRequest, opts ...grpc.CallOption) (*ClaudeTokenStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaudeTokenStatus)
	err := c.cc.Invoke(ctx, Ai_SetClaudeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) ClaudeStatus(ctx context.Context, in *ClaudeStatusRequest, opts ...grpc.CallOption) (*ClaudeTokenStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaudeTokenStatus)
	err := c.cc.Invoke(ctx, Ai_ClaudeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility.
//
// Ai to agent ze skillami (czytanie pliku, sprawdzanie eventów). PLANUJE przed
// wykonaniem, a postęp (plan, użyte narzędzia, odpowiedź) strumieniuje.
type AiServer interface {
	// Ask to agent ze skillami — DWUKIERUNKOWY stream. Aplikacja wysyła start (zadanie +
	// kontekst) oraz odpowiedzi na żądania skilli; serwer strumieniuje plan, użyte narzędzia,
	// żądania skilli (read_file/list_dir/get_graph wykonywane przez aplikację) i odpowiedź.
	Ask(grpc.BidiStreamingServer[AskClientMsg, AskEvent]) error
	// Generate to proste wywołanie LLM — wszystko inne (np. opis plików w
	// scannerze) idzie przez ten serwis, by LLM był w jednym miejscu.
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	// Model zwraca nazwę aktualnie używanego modelu.
	Model(context.Context, *ModelRequest) (*ModelResponse, error)
	// SetProvider podmienia dostawcę LLM w locie (np. ollama → claude headless).
	SetProvider(context.Context, *SetProviderRequest) (*ModelResponse, error)
	// SetClaudeToken zapisuje długoterminowy token OAuth (claude setup-token) używany
	// przez `claude -p` w trybie headless. Serwis persystuje go u siebie (wolumen).
	SetClaudeToken(context.Context, *SetClaudeTokenRequest) (*ClaudeTokenStatus, error)
	// ClaudeStatus mówi, czy serwis ma zapisany token Claude (do bramki logowania w UI).
	ClaudeStatus(context.Context, *ClaudeStatusRequest) (*ClaudeTokenStatus, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServer struct{}

func (UnimplementedAiServer) Ask(grpc.BidiStreamingServer[AskClientMsg, AskEvent]) error {
	return status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAiServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAiServer) Model(context.Context, *ModelRequest) (*ModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Model not implemented")
}
func (UnimplementedAiServer) SetProvider(context.Context, *SetProviderRequest) (*ModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProvider not implemented")
}
func (UnimplementedAiServer) SetClaudeToken(context.Context, *SetClaudeTokenRequest) (*ClaudeTokenStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClaudeToken not implemented")
}
func (UnimplementedAiServer) ClaudeStatus(context.Context, *ClaudeStatusRequest) (*ClaudeTokenStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaudeStatus not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}
func (UnimplementedAiServer) testEmbeddedByValue()            {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	// If the following call panics, it indicates UnimplementedAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_Ask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AiServer).Ask(&grpc.GenericServerStream[AskClientMsg, AskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_AskServer = grpc.BidiStreamingServer[AskClientMsg, AskEvent]

func _Ai_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_Model_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).Model(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_Model_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).Model(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_SetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).SetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_SetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).SetProvider(ctx, req.(*SetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_SetClaudeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClaudeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).SetClaudeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_SetClaudeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).SetClaudeToken(ctx, req.(*SetClaudeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_ClaudeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaudeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).ClaudeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_ClaudeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).ClaudeStatus(ctx, req.(*ClaudeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Ai_Generate_Handler,
		},
		{
			MethodName: "Model",
			Handler:    _Ai_Model_Handler,
		},
		{
			MethodName: "SetProvider",
			Handler:    _Ai_SetProvider_Handler,
		},
		{
			MethodName: "SetClaudeToken",
			Handler:    _Ai_SetClaudeToken_Handler,
		},
		{
			MethodName: "ClaudeStatus",
			Handler:    _Ai_ClaudeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ask",
			Handler:       _Ai_Ask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ai/v1/ai.proto",
}
