// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: scripting/v1/scripting.proto

package scriptingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{0}
}

type ScriptId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptId) Reset() {
	*x = ScriptId{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptId) ProtoMessage() {}

func (x *ScriptId) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptId.ProtoReflect.Descriptor instead.
func (*ScriptId) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{1}
}

func (x *ScriptId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Script struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Project       string                 `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`                       // project folder the script is pinned to ("" = global)
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{2}
}

func (x *Script) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Script) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Script) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Script) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ScriptQuery filters the script list. project == "" → all; otherwise global ones
// (project == "") + those pinned to this project.
type ScriptQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptQuery) Reset() {
	*x = ScriptQuery{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptQuery) ProtoMessage() {}

func (x *ScriptQuery) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptQuery.ProtoReflect.Descriptor instead.
func (*ScriptQuery) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{3}
}

func (x *ScriptQuery) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type Scripts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*Script              `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scripts) Reset() {
	*x = Scripts{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scripts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scripts) ProtoMessage() {}

func (x *Scripts) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scripts.ProtoReflect.Descriptor instead.
func (*Scripts) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{4}
}

func (x *Scripts) GetScripts() []*Script {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_scripting_v1_scripting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_scripting_v1_scripting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_scripting_v1_scripting_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_scripting_v1_scripting_proto protoreflect.FileDescriptor

const file_scripting_v1_scripting_proto_rawDesc = "" +
	"\n" +
	"\x1cscripting/v1/scripting.proto\x12\fscripting.v1\"\a\n" +
	"\x05Empty\"\x1a\n" +
	"\bScriptId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9e\x01\n" +
	"\x06Script\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"'\n" +
	"\vScriptQuery\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"9\n" +
	"\aScripts\x12.\n" +
	"\ascripts\x18\x01 \x03(\v2\x14.scripting.v1.ScriptR\ascripts\"\x1e\n" +
	"\fDeleteResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x85\x02\n" +
	"\tScripting\x12?\n" +
	"\vListScripts\x12\x19.scripting.v1.ScriptQuery\x1a\x15.scripting.v1.Scripts\x129\n" +
	"\tGetScript\x12\x16.scripting.v1.ScriptId\x1a\x14.scripting.v1.Script\x128\n" +
	"\n" +
	"SaveScript\x12\x14.scripting.v1.Script\x1a\x14.scripting.v1.Script\x12B\n" +
	"\fDeleteScript\x12\x16.scripting.v1.ScriptId\x1a\x1a.scripting.v1.DeleteResultBCZAgithub.com/filipgorny/ai-architect/proto/scripting/v1;scriptingv1b\x06proto3"

var (
	file_scripting_v1_scripting_proto_rawDescOnce sync.Once
	file_scripting_v1_scripting_proto_rawDescData []byte
)

func file_scripting_v1_scripting_proto_rawDescGZIP() []byte {
	file_scripting_v1_scripting_proto_rawDescOnce.Do(func() {
		file_scripting_v1_scripting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scripting_v1_scripting_proto_rawDesc), len(file_scripting_v1_scripting_proto_rawDesc)))
	})
	return file_scripting_v1_scripting_proto_rawDescData
}

var file_scripting_v1_scripting_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scripting_v1_scripting_proto_goTypes = []any{
	(*Empty)(nil),        // 0: scripting.v1.Empty
	(*ScriptId)(nil),     // 1: scripting.v1.ScriptId
	(*Script)(nil),       // 2: scripting.v1.Script
	(*ScriptQuery)(nil),  // 3: scripting.v1.ScriptQuery
	(*Scripts)(nil),      // 4: scripting.v1.Scripts
	(*DeleteResult)(nil), // 5: scripting.v1.DeleteResult
}
var file_scripting_v1_scripting_proto_depIdxs = []int32{
	2, // 0: scripting.v1.Scripts.scripts:type_name -> scripting.v1.Script
	3, // 1: scripting.v1.Scripting.ListScripts:input_type -> scripting.v1.ScriptQuery
	1, // 2: scripting.v1.Scripting.GetScript:input_type -> scripting.v1.ScriptId
	2, // 3: scripting.v1.Scripting.SaveScript:input_type -> scripting.v1.Script
	1, // 4: scripting.v1.Scripting.DeleteScript:input_type -> scripting.v1.ScriptId
	4, // 5: scripting.v1.Scripting.ListScripts:output_type -> scripting.v1.Scripts
	2, // 6: scripting.v1.Scripting.GetScript:output_type -> scripting.v1.Script
	2, // 7: scripting.v1.Scripting.SaveScript:output_type -> scripting.v1.Script
	5, // 8: scripting.v1.Scripting.DeleteScript:output_type -> scripting.v1.DeleteResult
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scripting_v1_scripting_proto_init() }
func file_scripting_v1_scripting_proto_init() {
	if File_scripting_v1_scripting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scripting_v1_scripting_proto_rawDesc), len(file_scripting_v1_scripting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scripting_v1_scripting_proto_goTypes,
		DependencyIndexes: file_scripting_v1_scripting_proto_depIdxs,
		MessageInfos:      file_scripting_v1_scripting_proto_msgTypes,
	}.Build()
	File_scripting_v1_scripting_proto = out.File
	file_scripting_v1_scripting_proto_goTypes = nil
	file_scripting_v1_scripting_proto_depIdxs = nil
}
