// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // note | change | ai-edit | scan | ...
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	AppId         int64                  `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	File          string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`                             // powiązanie z plikiem (ścieżka)
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // powiązanie z nodem (np. "controller:UsersController")
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix sekundy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Event) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId         int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ListRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_proto_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_events_v1_events_proto protoreflect.FileDescriptor

const file_proto_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/events/v1/events.proto\x12\tevents.v1\"\xb8\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"g\n" +
	"\vListRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"5\n" +
	"\tEventList\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.events.v1.EventR\x06events2m\n" +
	"\x06Events\x12-\n" +
	"\aPublish\x12\x10.events.v1.Event\x1a\x10.events.v1.Event\x124\n" +
	"\x04List\x12\x16.events.v1.ListRequest\x1a\x14.events.v1.EventListB=Z;github.com/filipgorny/ai-architect/proto/events/v1;eventsv1b\x06proto3"

var (
	file_proto_events_v1_events_proto_rawDescOnce sync.Once
	file_proto_events_v1_events_proto_rawDescData []byte
)

func file_proto_events_v1_events_proto_rawDescGZIP() []byte {
	file_proto_events_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_v1_events_proto_rawDesc), len(file_proto_events_v1_events_proto_rawDesc)))
	})
	return file_proto_events_v1_events_proto_rawDescData
}

var file_proto_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_events_v1_events_proto_goTypes = []any{
	(*Event)(nil),       // 0: events.v1.Event
	(*ListRequest)(nil), // 1: events.v1.ListRequest
	(*EventList)(nil),   // 2: events.v1.EventList
}
var file_proto_events_v1_events_proto_depIdxs = []int32{
	0, // 0: events.v1.EventList.events:type_name -> events.v1.Event
	0, // 1: events.v1.Events.Publish:input_type -> events.v1.Event
	1, // 2: events.v1.Events.List:input_type -> events.v1.ListRequest
	0, // 3: events.v1.Events.Publish:output_type -> events.v1.Event
	2, // 4: events.v1.Events.List:output_type -> events.v1.EventList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_events_v1_events_proto_init() }
func file_proto_events_v1_events_proto_init() {
	if File_proto_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_v1_events_proto_rawDesc), len(file_proto_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_events_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_events_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_events_v1_events_proto_msgTypes,
	}.Build()
	File_proto_events_v1_events_proto = out.File
	file_proto_events_v1_events_proto_goTypes = nil
	file_proto_events_v1_events_proto_depIdxs = nil
}
