// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/scanner/v1/scanner.proto

package scannerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_INFO              Level = 1
	Level_WARN              Level = 2
	Level_ERROR             Level = 3
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"INFO":              1,
		"WARN":              2,
		"ERROR":             3,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scanner_v1_scanner_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_proto_scanner_v1_scanner_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{0}
}

type LinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // absolute path of the analyzed file
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // current (possibly unsaved) buffer content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinksRequest) Reset() {
	*x = LinksRequest{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksRequest) ProtoMessage() {}

func (x *LinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksRequest.ProtoReflect.Descriptor instead.
func (*LinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *LinksRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LinksRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CodeLink is a clickable span in the source that resolves to a definition location.
// Positions are 0-based; columns are byte offsets within the line.
type CodeLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromLine      uint32                 `protobuf:"varint,1,opt,name=from_line,json=fromLine,proto3" json:"from_line,omitempty"`
	FromCol       uint32                 `protobuf:"varint,2,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToLine        uint32                 `protobuf:"varint,3,opt,name=to_line,json=toLine,proto3" json:"to_line,omitempty"`
	ToCol         uint32                 `protobuf:"varint,4,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	TargetPath    string                 `protobuf:"bytes,5,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`  // absolute path of the resolved file ("" if unresolved)
	TargetLine    uint32                 `protobuf:"varint,6,opt,name=target_line,json=targetLine,proto3" json:"target_line,omitempty"` // 0-based line of the definition (0 if unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeLink) Reset() {
	*x = CodeLink{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeLink) ProtoMessage() {}

func (x *CodeLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeLink.ProtoReflect.Descriptor instead.
func (*CodeLink) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *CodeLink) GetFromLine() uint32 {
	if x != nil {
		return x.FromLine
	}
	return 0
}

func (x *CodeLink) GetFromCol() uint32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *CodeLink) GetToLine() uint32 {
	if x != nil {
		return x.ToLine
	}
	return 0
}

func (x *CodeLink) GetToCol() uint32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *CodeLink) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *CodeLink) GetTargetLine() uint32 {
	if x != nil {
		return x.TargetLine
	}
	return 0
}

type LinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*CodeLink            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinksResponse) Reset() {
	*x = LinksResponse{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksResponse) ProtoMessage() {}

func (x *LinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksResponse.ProtoReflect.Descriptor instead.
func (*LinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *LinksResponse) GetLinks() []*CodeLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ścieżka do pojedynczej aplikacji ALBO do monorepo.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScanRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ScanAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // absolutna ścieżka katalogu aplikacji
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanAppRequest) Reset() {
	*x = ScanAppRequest{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAppRequest) ProtoMessage() {}

func (x *ScanAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAppRequest.ProtoReflect.Descriptor instead.
func (*ScanAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *ScanAppRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ScanAppRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// LogLine to wolnotekstowy log pokazywany w konsoli TUI.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Level                  `protobuf:"varint,1,opt,name=level,proto3,enum=scanner.v1.Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *LogLine) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ProjectDetected emitowane po rozpoznaniu skanowanego roota (app lub monorepo).
type ProjectDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	GitPath       string                 `protobuf:"bytes,3,opt,name=git_path,json=gitPath,proto3" json:"git_path,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // "typescript-app" | "monorepo"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDetected) Reset() {
	*x = ProjectDetected{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDetected) ProtoMessage() {}

func (x *ProjectDetected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDetected.ProtoReflect.Descriptor instead.
func (*ProjectDetected) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectDetected) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectDetected) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ProjectDetected) GetGitPath() string {
	if x != nil {
		return x.GitPath
	}
	return ""
}

func (x *ProjectDetected) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// AppDetected emitowane dla każdej aplikacji (root przy pojedynczej app, albo
// każdy workspace w monorepo) wraz z rozpoznanym frameworkiem i dostępnością pluginu.
type AppDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`           // względem roota projektu
	Framework     string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"` // "nestjs" | "" gdy nierozpoznany
	HasPlugin     bool                   `protobuf:"varint,6,opt,name=has_plugin,json=hasPlugin,proto3" json:"has_plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppDetected) Reset() {
	*x = AppDetected{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetected) ProtoMessage() {}

func (x *AppDetected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetected.ProtoReflect.Descriptor instead.
func (*AppDetected) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *AppDetected) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppDetected) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AppDetected) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDetected) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AppDetected) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *AppDetected) GetHasPlugin() bool {
	if x != nil {
		return x.HasPlugin
	}
	return false
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Imports       []string               `protobuf:"bytes,5,rep,name=imports,proto3" json:"imports,omitempty"`
	Controllers   []string               `protobuf:"bytes,6,rep,name=controllers,proto3" json:"controllers,omitempty"`
	Providers     []string               `protobuf:"bytes,7,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *Module) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Module) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Module) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *Module) GetControllers() []string {
	if x != nil {
		return x.Controllers
	}
	return nil
}

func (x *Module) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Controller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Route         string                 `protobuf:"bytes,5,opt,name=route,proto3" json:"route,omitempty"`
	Methods       []string               `protobuf:"bytes,6,rep,name=methods,proto3" json:"methods,omitempty"`           // funkcje (klocek w grafie)
	Dependencies  []string               `protobuf:"bytes,7,rep,name=dependencies,proto3" json:"dependencies,omitempty"` // wstrzykiwane typy (krawędzie grafu)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Controller) Reset() {
	*x = Controller{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Controller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controller) ProtoMessage() {}

func (x *Controller) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controller.ProtoReflect.Descriptor instead.
func (*Controller) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *Controller) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Controller) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Controller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Controller) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Controller) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Controller) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Controller) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Methods       []string               `protobuf:"bytes,5,rep,name=methods,proto3" json:"methods,omitempty"`
	Dependencies  []string               `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Service) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Service) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Service) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Renders       []string               `protobuf:"bytes,5,rep,name=renders,proto3" json:"renders,omitempty"` // renderowane komponenty (krawędzie grafu)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *Component) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Component) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Component) GetRenders() []string {
	if x != nil {
		return x.Renders
	}
	return nil
}

// FileDescribed emitowane po opisaniu pliku przez LLM i zapisaniu do files.
type FileDescribed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	AppId         int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDescribed) Reset() {
	*x = FileDescribed{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDescribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDescribed) ProtoMessage() {}

func (x *FileDescribed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDescribed.ProtoReflect.Descriptor instead.
func (*FileDescribed) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{12}
}

func (x *FileDescribed) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileDescribed) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *FileDescribed) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDescribed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ScanDone struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppsScanned     int32                  `protobuf:"varint,1,opt,name=apps_scanned,json=appsScanned,proto3" json:"apps_scanned,omitempty"`
	FilesScanned    int32                  `protobuf:"varint,2,opt,name=files_scanned,json=filesScanned,proto3" json:"files_scanned,omitempty"`
	EntitiesScanned int32                  `protobuf:"varint,3,opt,name=entities_scanned,json=entitiesScanned,proto3" json:"entities_scanned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScanDone) Reset() {
	*x = ScanDone{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDone) ProtoMessage() {}

func (x *ScanDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDone.ProtoReflect.Descriptor instead.
func (*ScanDone) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{13}
}

func (x *ScanDone) GetAppsScanned() int32 {
	if x != nil {
		return x.AppsScanned
	}
	return 0
}

func (x *ScanDone) GetFilesScanned() int32 {
	if x != nil {
		return x.FilesScanned
	}
	return 0
}

func (x *ScanDone) GetEntitiesScanned() int32 {
	if x != nil {
		return x.EntitiesScanned
	}
	return 0
}

// Link to skierowana krawędź do innego bytu (po nazwie) z etykietą relacji.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{14}
}

func (x *Link) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Link) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Element to byt-matka: moduł/kontroler/serwis/komponent/klasa/funkcja.
type Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Framework     string                 `protobuf:"bytes,1,opt,name=framework,proto3" json:"framework,omitempty"` // plugin źródłowy (nestjs|react)
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`           // module|controller|service|component|class|function
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Route         string                 `protobuf:"bytes,5,opt,name=route,proto3" json:"route,omitempty"`
	Functions     []string               `protobuf:"bytes,6,rep,name=functions,proto3" json:"functions,omitempty"`
	Links         []*Link                `protobuf:"bytes,7,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{15}
}

func (x *Element) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Element) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Element) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Element) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Element) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Element) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type ScanEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ScanEvent_Log
	//	*ScanEvent_Project
	//	*ScanEvent_App
	//	*ScanEvent_File
	//	*ScanEvent_Done
	//	*ScanEvent_Element
	Event         isScanEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEvent) Reset() {
	*x = ScanEvent{}
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEvent) ProtoMessage() {}

func (x *ScanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_v1_scanner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEvent.ProtoReflect.Descriptor instead.
func (*ScanEvent) Descriptor() ([]byte, []int) {
	return file_proto_scanner_v1_scanner_proto_rawDescGZIP(), []int{16}
}

func (x *ScanEvent) GetEvent() isScanEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ScanEvent) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ScanEvent) GetProject() *ProjectDetected {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *ScanEvent) GetApp() *AppDetected {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_App); ok {
			return x.App
		}
	}
	return nil
}

func (x *ScanEvent) GetFile() *FileDescribed {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *ScanEvent) GetDone() *ScanDone {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ScanEvent) GetElement() *Element {
	if x != nil {
		if x, ok := x.Event.(*ScanEvent_Element); ok {
			return x.Element
		}
	}
	return nil
}

type isScanEvent_Event interface {
	isScanEvent_Event()
}

type ScanEvent_Log struct {
	Log *LogLine `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type ScanEvent_Project struct {
	Project *ProjectDetected `protobuf:"bytes,2,opt,name=project,proto3,oneof"`
}

type ScanEvent_App struct {
	App *AppDetected `protobuf:"bytes,3,opt,name=app,proto3,oneof"`
}

type ScanEvent_File struct {
	File *FileDescribed `protobuf:"bytes,7,opt,name=file,proto3,oneof"`
}

type ScanEvent_Done struct {
	Done *ScanDone `protobuf:"bytes,8,opt,name=done,proto3,oneof"`
}

type ScanEvent_Element struct {
	Element *Element `protobuf:"bytes,10,opt,name=element,proto3,oneof"`
}

func (*ScanEvent_Log) isScanEvent_Event() {}

func (*ScanEvent_Project) isScanEvent_Event() {}

func (*ScanEvent_App) isScanEvent_Event() {}

func (*ScanEvent_File) isScanEvent_Event() {}

func (*ScanEvent_Done) isScanEvent_Event() {}

func (*ScanEvent_Element) isScanEvent_Event() {}

var File_proto_scanner_v1_scanner_proto protoreflect.FileDescriptor

const file_proto_scanner_v1_scanner_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/scanner/v1/scanner.proto\x12\n" +
	"scanner.v1\"<\n" +
	"\fLinksRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb4\x01\n" +
	"\bCodeLink\x12\x1b\n" +
	"\tfrom_line\x18\x01 \x01(\rR\bfromLine\x12\x19\n" +
	"\bfrom_col\x18\x02 \x01(\rR\afromCol\x12\x17\n" +
	"\ato_line\x18\x03 \x01(\rR\x06toLine\x12\x15\n" +
	"\x06to_col\x18\x04 \x01(\rR\x05toCol\x12\x1f\n" +
	"\vtarget_path\x18\x05 \x01(\tR\n" +
	"targetPath\x12\x1f\n" +
	"\vtarget_line\x18\x06 \x01(\rR\n" +
	"targetLine\";\n" +
	"\rLinksResponse\x12*\n" +
	"\x05links\x18\x01 \x03(\v2\x14.scanner.v1.CodeLinkR\x05links\"!\n" +
	"\vScanRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\";\n" +
	"\x0eScanAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"L\n" +
	"\aLogLine\x12'\n" +
	"\x05level\x18\x01 \x01(\x0e2\x11.scanner.v1.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x0fProjectDetected\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x19\n" +
	"\bgit_path\x18\x03 \x01(\tR\agitPath\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"\xa8\x01\n" +
	"\vAppDetected\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12\x1d\n" +
	"\n" +
	"has_plugin\x18\x06 \x01(\bR\thasPlugin\"\xb1\x01\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x18\n" +
	"\aimports\x18\x05 \x03(\tR\aimports\x12 \n" +
	"\vcontrollers\x18\x06 \x03(\tR\vcontrollers\x12\x1c\n" +
	"\tproviders\x18\a \x03(\tR\tproviders\"\xaf\x01\n" +
	"\n" +
	"Controller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x14\n" +
	"\x05route\x18\x05 \x01(\tR\x05route\x12\x18\n" +
	"\amethods\x18\x06 \x03(\tR\amethods\x12\"\n" +
	"\fdependencies\x18\a \x03(\tR\fdependencies\"\x96\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x18\n" +
	"\amethods\x18\x05 \x03(\tR\amethods\x12\"\n" +
	"\fdependencies\x18\x06 \x03(\tR\fdependencies\"t\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x18\n" +
	"\arenders\x18\x05 \x03(\tR\arenders\"u\n" +
	"\rFileDescribed\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"}\n" +
	"\bScanDone\x12!\n" +
	"\fapps_scanned\x18\x01 \x01(\x05R\vappsScanned\x12#\n" +
	"\rfiles_scanned\x18\x02 \x01(\x05R\ffilesScanned\x12)\n" +
	"\x10entities_scanned\x18\x03 \x01(\x05R\x0fentitiesScanned\"4\n" +
	"\x04Link\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xbf\x01\n" +
	"\aElement\x12\x1c\n" +
	"\tframework\x18\x01 \x01(\tR\tframework\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x14\n" +
	"\x05route\x18\x05 \x01(\tR\x05route\x12\x1c\n" +
	"\tfunctions\x18\x06 \x03(\tR\tfunctions\x12&\n" +
	"\x05links\x18\a \x03(\v2\x10.scanner.v1.LinkR\x05links\"\xb1\x02\n" +
	"\tScanEvent\x12'\n" +
	"\x03log\x18\x01 \x01(\v2\x13.scanner.v1.LogLineH\x00R\x03log\x127\n" +
	"\aproject\x18\x02 \x01(\v2\x1b.scanner.v1.ProjectDetectedH\x00R\aproject\x12+\n" +
	"\x03app\x18\x03 \x01(\v2\x17.scanner.v1.AppDetectedH\x00R\x03app\x12/\n" +
	"\x04file\x18\a \x01(\v2\x19.scanner.v1.FileDescribedH\x00R\x04file\x12*\n" +
	"\x04done\x18\b \x01(\v2\x14.scanner.v1.ScanDoneH\x00R\x04done\x12/\n" +
	"\aelement\x18\n" +
	" \x01(\v2\x13.scanner.v1.ElementH\x00R\aelementB\a\n" +
	"\x05event*=\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xc1\x01\n" +
	"\aScanner\x128\n" +
	"\x04Scan\x12\x17.scanner.v1.ScanRequest\x1a\x15.scanner.v1.ScanEvent0\x01\x12>\n" +
	"\aScanApp\x12\x1a.scanner.v1.ScanAppRequest\x1a\x15.scanner.v1.ScanEvent0\x01\x12<\n" +
	"\x05Links\x12\x18.scanner.v1.LinksRequest\x1a\x19.scanner.v1.LinksResponseB?Z=github.com/filipgorny/ai-architect/proto/scanner/v1;scannerv1b\x06proto3"

var (
	file_proto_scanner_v1_scanner_proto_rawDescOnce sync.Once
	file_proto_scanner_v1_scanner_proto_rawDescData []byte
)

func file_proto_scanner_v1_scanner_proto_rawDescGZIP() []byte {
	file_proto_scanner_v1_scanner_proto_rawDescOnce.Do(func() {
		file_proto_scanner_v1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scanner_v1_scanner_proto_rawDesc), len(file_proto_scanner_v1_scanner_proto_rawDesc)))
	})
	return file_proto_scanner_v1_scanner_proto_rawDescData
}

var file_proto_scanner_v1_scanner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scanner_v1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_scanner_v1_scanner_proto_goTypes = []any{
	(Level)(0),              // 0: scanner.v1.Level
	(*LinksRequest)(nil),    // 1: scanner.v1.LinksRequest
	(*CodeLink)(nil),        // 2: scanner.v1.CodeLink
	(*LinksResponse)(nil),   // 3: scanner.v1.LinksResponse
	(*ScanRequest)(nil),     // 4: scanner.v1.ScanRequest
	(*ScanAppRequest)(nil),  // 5: scanner.v1.ScanAppRequest
	(*LogLine)(nil),         // 6: scanner.v1.LogLine
	(*ProjectDetected)(nil), // 7: scanner.v1.ProjectDetected
	(*AppDetected)(nil),     // 8: scanner.v1.AppDetected
	(*Module)(nil),          // 9: scanner.v1.Module
	(*Controller)(nil),      // 10: scanner.v1.Controller
	(*Service)(nil),         // 11: scanner.v1.Service
	(*Component)(nil),       // 12: scanner.v1.Component
	(*FileDescribed)(nil),   // 13: scanner.v1.FileDescribed
	(*ScanDone)(nil),        // 14: scanner.v1.ScanDone
	(*Link)(nil),            // 15: scanner.v1.Link
	(*Element)(nil),         // 16: scanner.v1.Element
	(*ScanEvent)(nil),       // 17: scanner.v1.ScanEvent
}
var file_proto_scanner_v1_scanner_proto_depIdxs = []int32{
	2,  // 0: scanner.v1.LinksResponse.links:type_name -> scanner.v1.CodeLink
	0,  // 1: scanner.v1.LogLine.level:type_name -> scanner.v1.Level
	15, // 2: scanner.v1.Element.links:type_name -> scanner.v1.Link
	6,  // 3: scanner.v1.ScanEvent.log:type_name -> scanner.v1.LogLine
	7,  // 4: scanner.v1.ScanEvent.project:type_name -> scanner.v1.ProjectDetected
	8,  // 5: scanner.v1.ScanEvent.app:type_name -> scanner.v1.AppDetected
	13, // 6: scanner.v1.ScanEvent.file:type_name -> scanner.v1.FileDescribed
	14, // 7: scanner.v1.ScanEvent.done:type_name -> scanner.v1.ScanDone
	16, // 8: scanner.v1.ScanEvent.element:type_name -> scanner.v1.Element
	4,  // 9: scanner.v1.Scanner.Scan:input_type -> scanner.v1.ScanRequest
	5,  // 10: scanner.v1.Scanner.ScanApp:input_type -> scanner.v1.ScanAppRequest
	1,  // 11: scanner.v1.Scanner.Links:input_type -> scanner.v1.LinksRequest
	17, // 12: scanner.v1.Scanner.Scan:output_type -> scanner.v1.ScanEvent
	17, // 13: scanner.v1.Scanner.ScanApp:output_type -> scanner.v1.ScanEvent
	3,  // 14: scanner.v1.Scanner.Links:output_type -> scanner.v1.LinksResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_scanner_v1_scanner_proto_init() }
func file_proto_scanner_v1_scanner_proto_init() {
	if File_proto_scanner_v1_scanner_proto != nil {
		return
	}
	file_proto_scanner_v1_scanner_proto_msgTypes[16].OneofWrappers = []any{
		(*ScanEvent_Log)(nil),
		(*ScanEvent_Project)(nil),
		(*ScanEvent_App)(nil),
		(*ScanEvent_File)(nil),
		(*ScanEvent_Done)(nil),
		(*ScanEvent_Element)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scanner_v1_scanner_proto_rawDesc), len(file_proto_scanner_v1_scanner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scanner_v1_scanner_proto_goTypes,
		DependencyIndexes: file_proto_scanner_v1_scanner_proto_depIdxs,
		EnumInfos:         file_proto_scanner_v1_scanner_proto_enumTypes,
		MessageInfos:      file_proto_scanner_v1_scanner_proto_msgTypes,
	}.Build()
	File_proto_scanner_v1_scanner_proto = out.File
	file_proto_scanner_v1_scanner_proto_goTypes = nil
	file_proto_scanner_v1_scanner_proto_depIdxs = nil
}
