// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/scanner/v1/scanner.proto

package scannerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scanner_Scan_FullMethodName    = "/scanner.v1.Scanner/Scan"
	Scanner_ScanApp_FullMethodName = "/scanner.v1.Scanner/ScanApp"
	Scanner_Links_FullMethodName   = "/scanner.v1.Scanner/Links"
)

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scanner skanuje katalog projektu, rozpoznaje jego typ i framework, ekstrahuje
// encje (przez pluginy), opisuje pliki modelem LLM i strumieniuje zdarzenia
// (logi + encje) z powrotem do klienta TUI.
type ScannerClient interface {
	// Scan robi skan wierzchni: rozpoznaje typ projektu i wylicza aplikacje
	// (dla monorepo BEZ głębokiej analizy — to robi ScanApp na żądanie).
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error)
	// ScanApp robi głęboki skan pojedynczej aplikacji: ekstrakcja encji (klasy,
	// kontrolery, serwisy, moduły) i zapis pod jej app_id.
	ScanApp(ctx context.Context, in *ScanAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error)
	// Links analyzes a single source file (tree-sitter; LSP when available) and returns the
	// navigable code links in it — import paths and imported-symbol usages — each resolved to
	// the file (and definition line) it points at. Drives go-to-definition in the editor.
	Links(ctx context.Context, in *LinksRequest, opts ...grpc.CallOption) (*LinksResponse, error)
}

type scannerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerClient(cc grpc.ClientConnInterface) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[0], Scanner_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ScanClient = grpc.ServerStreamingClient[ScanEvent]

func (c *scannerClient) ScanApp(ctx context.Context, in *ScanAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[1], Scanner_ScanApp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanAppRequest, ScanEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ScanAppClient = grpc.ServerStreamingClient[ScanEvent]

func (c *scannerClient) Links(ctx context.Context, in *LinksRequest, opts ...grpc.CallOption) (*LinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinksResponse)
	err := c.cc.Invoke(ctx, Scanner_Links_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
// All implementations must embed UnimplementedScannerServer
// for forward compatibility.
//
// Scanner skanuje katalog projektu, rozpoznaje jego typ i framework, ekstrahuje
// encje (przez pluginy), opisuje pliki modelem LLM i strumieniuje zdarzenia
// (logi + encje) z powrotem do klienta TUI.
type ScannerServer interface {
	// Scan robi skan wierzchni: rozpoznaje typ projektu i wylicza aplikacje
	// (dla monorepo BEZ głębokiej analizy — to robi ScanApp na żądanie).
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanEvent]) error
	// ScanApp robi głęboki skan pojedynczej aplikacji: ekstrakcja encji (klasy,
	// kontrolery, serwisy, moduły) i zapis pod jej app_id.
	ScanApp(*ScanAppRequest, grpc.ServerStreamingServer[ScanEvent]) error
	// Links analyzes a single source file (tree-sitter; LSP when available) and returns the
	// navigable code links in it — import paths and imported-symbol usages — each resolved to
	// the file (and definition line) it points at. Drives go-to-definition in the editor.
	Links(context.Context, *LinksRequest) (*LinksResponse, error)
	mustEmbedUnimplementedScannerServer()
}

// UnimplementedScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerServer struct{}

func (UnimplementedScannerServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanEvent]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedScannerServer) ScanApp(*ScanAppRequest, grpc.ServerStreamingServer[ScanEvent]) error {
	return status.Error(codes.Unimplemented, "method ScanApp not implemented")
}
func (UnimplementedScannerServer) Links(context.Context, *LinksRequest) (*LinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Links not implemented")
}
func (UnimplementedScannerServer) mustEmbedUnimplementedScannerServer() {}
func (UnimplementedScannerServer) testEmbeddedByValue()                 {}

// UnsafeScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServer will
// result in compilation errors.
type UnsafeScannerServer interface {
	mustEmbedUnimplementedScannerServer()
}

func RegisterScannerServer(s grpc.ServiceRegistrar, srv ScannerServer) {
	// If the following call panics, it indicates UnimplementedScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scanner_ServiceDesc, srv)
}

func _Scanner_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScannerServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ScanServer = grpc.ServerStreamingServer[ScanEvent]

func _Scanner_ScanApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanAppRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScannerServer).ScanApp(m, &grpc.GenericServerStream[ScanAppRequest, ScanEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ScanAppServer = grpc.ServerStreamingServer[ScanEvent]

func _Scanner_Links_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Links(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scanner_Links_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Links(ctx, req.(*LinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scanner_ServiceDesc is the grpc.ServiceDesc for Scanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.v1.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Links",
			Handler:    _Scanner_Links_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _Scanner_Scan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ScanApp",
			Handler:       _Scanner_ScanApp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/scanner/v1/scanner.proto",
}
