// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiEditRequest) Reset() {
	*x = AiEditRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiEditRequest) ProtoMessage() {}

func (x *AiEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiEditRequest.ProtoReflect.Descriptor instead.
func (*AiEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AiEditRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AiEditRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AiEditRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type AiEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiEditResponse) Reset() {
	*x = AiEditResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiEditResponse) ProtoMessage() {}

func (x *AiEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiEditResponse.ProtoReflect.Descriptor instead.
func (*AiEditResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AiEditResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type EventInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	AppId         int64                  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	File          string                 `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInput) Reset() {
	*x = EventInput{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInput) ProtoMessage() {}

func (x *EventInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInput.ProtoReflect.Descriptor instead.
func (*EventInput) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *EventInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventInput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EventInput) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EventInput) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *EventInput) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	AppId         int64                  `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	File          string                 `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Event) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type EventQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId         int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQuery) Reset() {
	*x = EventQuery{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQuery) ProtoMessage() {}

func (x *EventQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQuery.ProtoReflect.Descriptor instead.
func (*EventQuery) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *EventQuery) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *EventQuery) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventQuery) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EventQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ScanAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanAppRequest) Reset() {
	*x = ScanAppRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanAppRequest) ProtoMessage() {}

func (x *ScanAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanAppRequest.ProtoReflect.Descriptor instead.
func (*ScanAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ScanAppRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type AppGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGraphRequest) Reset() {
	*x = AppGraphRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGraphRequest) ProtoMessage() {}

func (x *AppGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGraphRequest.ProtoReflect.Descriptor instead.
func (*AppGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *AppGraphRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

// Progress to uproszczone zdarzenie dla UI (modal z progress barem).
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // log do konsoli
	CurrentFile   string                 `protobuf:"bytes,2,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`     // nazwa aktualnie czytanego pliku
	FilesDone     int32                  `protobuf:"varint,3,opt,name=files_done,json=filesDone,proto3" json:"files_done,omitempty"`          // ile plików już opisano
	EntitiesDone  int32                  `protobuf:"varint,4,opt,name=entities_done,json=entitiesDone,proto3" json:"entities_done,omitempty"` // ile encji już wyciągnięto
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`                                     // koniec skanowania
	ProjectId     int64                  `protobuf:"varint,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`          // ustawione przy zdarzeniu projektu / na końcu
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *Progress) GetFilesDone() int32 {
	if x != nil {
		return x.FilesDone
	}
	return 0
}

func (x *Progress) GetEntitiesDone() int32 {
	if x != nil {
		return x.EntitiesDone
	}
	return 0
}

func (x *Progress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Progress) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type GraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 0 = ostatni przeskanowany projekt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRequest) Reset() {
	*x = GraphRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRequest) ProtoMessage() {}

func (x *GraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRequest.ProtoReflect.Descriptor instead.
func (*GraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *GraphRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

// Node to klocek grafu: moduł, kontroler lub serwis, z listą funkcji.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // np. "controller:UsersController"
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "module" | "controller" | "service"
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	App           string                 `protobuf:"bytes,5,opt,name=app,proto3" json:"app,omitempty"`                         // nazwa aplikacji (workspace)
	Functions     []string               `protobuf:"bytes,6,rep,name=functions,proto3" json:"functions,omitempty"`             // metody do wypisania w klocku
	Route         string                 `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`                     // ścieżka kontrolera (puste dla module/service)
	AppId         int64                  `protobuf:"varint,8,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`       // dla węzłów-serwisów (kind="service") w grafie monorepo
	Framework     string                 `protobuf:"bytes,9,opt,name=framework,proto3" json:"framework,omitempty"`             // framework aplikacji (dla węzłów-serwisów)
	AbsFile       string                 `protobuf:"bytes,10,opt,name=abs_file,json=absFile,proto3" json:"abs_file,omitempty"` // absolutna ścieżka pliku (do otwarcia w edytorze)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Node) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Node) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Node) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Node) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Node) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Node) GetAbsFile() string {
	if x != nil {
		return x.AbsFile
	}
	return ""
}

// Edge to połączenie kreską między bytami.
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"` // "import" | "controller" | "provider" | "injects"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *Graph) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Graph) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	GitPath       string                 `protobuf:"bytes,3,opt,name=git_path,json=gitPath,proto3" json:"git_path,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Project) GetGitPath() string {
	if x != nil {
		return x.GitPath
	}
	return ""
}

func (x *Project) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Projects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projects) Reset() {
	*x = Projects{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projects) ProtoMessage() {}

func (x *Projects) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projects.ProtoReflect.Descriptor instead.
func (*Projects) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *Projects) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

var File_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"O\n" +
	"\rAiEditRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\"$\n" +
	"\x0eAiEditResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x8e\x01\n" +
	"\n" +
	"EventInput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04file\x18\x05 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\"\xb8\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\x03R\x05appId\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"f\n" +
	"\n" +
	"EventQuery\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"6\n" +
	"\tEventList\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.gateway.v1.EventR\x06events\"\a\n" +
	"\x05Empty\"!\n" +
	"\vScanRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"'\n" +
	"\x0eScanAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\"(\n" +
	"\x0fAppGraphRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\"\xbe\x01\n" +
	"\bProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fcurrent_file\x18\x02 \x01(\tR\vcurrentFile\x12\x1d\n" +
	"\n" +
	"files_done\x18\x03 \x01(\x05R\tfilesDone\x12#\n" +
	"\rentities_done\x18\x04 \x01(\x05R\fentitiesDone\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\x03R\tprojectId\"-\n" +
	"\fGraphRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"\xe8\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x10\n" +
	"\x03app\x18\x05 \x01(\tR\x03app\x12\x1c\n" +
	"\tfunctions\x18\x06 \x03(\tR\tfunctions\x12\x14\n" +
	"\x05route\x18\a \x01(\tR\x05route\x12\x15\n" +
	"\x06app_id\x18\b \x01(\x03R\x05appId\x12\x1c\n" +
	"\tframework\x18\t \x01(\tR\tframework\x12\x19\n" +
	"\babs_file\x18\n" +
	" \x01(\tR\aabsFile\"@\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x8e\x01\n" +
	"\x05Graph\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12&\n" +
	"\x05nodes\x18\x03 \x03(\v2\x10.gateway.v1.NodeR\x05nodes\x12&\n" +
	"\x05edges\x18\x04 \x03(\v2\x10.gateway.v1.EdgeR\x05edges\"`\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x19\n" +
	"\bgit_path\x18\x03 \x01(\tR\agitPath\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\";\n" +
	"\bProjects\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.gateway.v1.ProjectR\bprojects2\xeb\x03\n" +
	"\aGateway\x127\n" +
	"\x04Scan\x12\x17.gateway.v1.ScanRequest\x1a\x14.gateway.v1.Progress0\x01\x127\n" +
	"\bGetGraph\x12\x18.gateway.v1.GraphRequest\x1a\x11.gateway.v1.Graph\x12=\n" +
	"\aScanApp\x12\x1a.gateway.v1.ScanAppRequest\x1a\x14.gateway.v1.Progress0\x01\x12=\n" +
	"\vGetAppGraph\x12\x1b.gateway.v1.AppGraphRequest\x1a\x11.gateway.v1.Graph\x127\n" +
	"\fListProjects\x12\x11.gateway.v1.Empty\x1a\x14.gateway.v1.Projects\x12?\n" +
	"\x06AiEdit\x12\x19.gateway.v1.AiEditRequest\x1a\x1a.gateway.v1.AiEditResponse\x129\n" +
	"\fPublishEvent\x12\x16.gateway.v1.EventInput\x1a\x11.gateway.v1.Event\x12;\n" +
	"\n" +
	"ListEvents\x12\x16.gateway.v1.EventQuery\x1a\x15.gateway.v1.EventListB?Z=github.com/filipgorny/ai-architect/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_v1_gateway_proto_rawDescData
}

var file_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*AiEditRequest)(nil),   // 0: gateway.v1.AiEditRequest
	(*AiEditResponse)(nil),  // 1: gateway.v1.AiEditResponse
	(*EventInput)(nil),      // 2: gateway.v1.EventInput
	(*Event)(nil),           // 3: gateway.v1.Event
	(*EventQuery)(nil),      // 4: gateway.v1.EventQuery
	(*EventList)(nil),       // 5: gateway.v1.EventList
	(*Empty)(nil),           // 6: gateway.v1.Empty
	(*ScanRequest)(nil),     // 7: gateway.v1.ScanRequest
	(*ScanAppRequest)(nil),  // 8: gateway.v1.ScanAppRequest
	(*AppGraphRequest)(nil), // 9: gateway.v1.AppGraphRequest
	(*Progress)(nil),        // 10: gateway.v1.Progress
	(*GraphRequest)(nil),    // 11: gateway.v1.GraphRequest
	(*Node)(nil),            // 12: gateway.v1.Node
	(*Edge)(nil),            // 13: gateway.v1.Edge
	(*Graph)(nil),           // 14: gateway.v1.Graph
	(*Project)(nil),         // 15: gateway.v1.Project
	(*Projects)(nil),        // 16: gateway.v1.Projects
}
var file_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	3,  // 0: gateway.v1.EventList.events:type_name -> gateway.v1.Event
	12, // 1: gateway.v1.Graph.nodes:type_name -> gateway.v1.Node
	13, // 2: gateway.v1.Graph.edges:type_name -> gateway.v1.Edge
	15, // 3: gateway.v1.Projects.projects:type_name -> gateway.v1.Project
	7,  // 4: gateway.v1.Gateway.Scan:input_type -> gateway.v1.ScanRequest
	11, // 5: gateway.v1.Gateway.GetGraph:input_type -> gateway.v1.GraphRequest
	8,  // 6: gateway.v1.Gateway.ScanApp:input_type -> gateway.v1.ScanAppRequest
	9,  // 7: gateway.v1.Gateway.GetAppGraph:input_type -> gateway.v1.AppGraphRequest
	6,  // 8: gateway.v1.Gateway.ListProjects:input_type -> gateway.v1.Empty
	0,  // 9: gateway.v1.Gateway.AiEdit:input_type -> gateway.v1.AiEditRequest
	2,  // 10: gateway.v1.Gateway.PublishEvent:input_type -> gateway.v1.EventInput
	4,  // 11: gateway.v1.Gateway.ListEvents:input_type -> gateway.v1.EventQuery
	10, // 12: gateway.v1.Gateway.Scan:output_type -> gateway.v1.Progress
	14, // 13: gateway.v1.Gateway.GetGraph:output_type -> gateway.v1.Graph
	10, // 14: gateway.v1.Gateway.ScanApp:output_type -> gateway.v1.Progress
	14, // 15: gateway.v1.Gateway.GetAppGraph:output_type -> gateway.v1.Graph
	16, // 16: gateway.v1.Gateway.ListProjects:output_type -> gateway.v1.Projects
	1,  // 17: gateway.v1.Gateway.AiEdit:output_type -> gateway.v1.AiEditResponse
	3,  // 18: gateway.v1.Gateway.PublishEvent:output_type -> gateway.v1.Event
	5,  // 19: gateway.v1.Gateway.ListEvents:output_type -> gateway.v1.EventList
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_gateway_proto_init() }
func file_proto_gateway_v1_gateway_proto_init() {
	if File_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_gateway_proto = out.File
	file_proto_gateway_v1_gateway_proto_goTypes = nil
	file_proto_gateway_v1_gateway_proto_depIdxs = nil
}
