// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gateway_Scan_FullMethodName              = "/gateway.v1.Gateway/Scan"
	Gateway_GetGraph_FullMethodName          = "/gateway.v1.Gateway/GetGraph"
	Gateway_ScanApp_FullMethodName           = "/gateway.v1.Gateway/ScanApp"
	Gateway_GetAppGraph_FullMethodName       = "/gateway.v1.Gateway/GetAppGraph"
	Gateway_ListProjects_FullMethodName      = "/gateway.v1.Gateway/ListProjects"
	Gateway_AiEdit_FullMethodName            = "/gateway.v1.Gateway/AiEdit"
	Gateway_AiModel_FullMethodName           = "/gateway.v1.Gateway/AiModel"
	Gateway_AiSetProvider_FullMethodName     = "/gateway.v1.Gateway/AiSetProvider"
	Gateway_AiReview_FullMethodName          = "/gateway.v1.Gateway/AiReview"
	Gateway_AiComplete_FullMethodName        = "/gateway.v1.Gateway/AiComplete"
	Gateway_PublishEvent_FullMethodName      = "/gateway.v1.Gateway/PublishEvent"
	Gateway_ListEvents_FullMethodName        = "/gateway.v1.Gateway/ListEvents"
	Gateway_ReadFile_FullMethodName          = "/gateway.v1.Gateway/ReadFile"
	Gateway_SaveFile_FullMethodName          = "/gateway.v1.Gateway/SaveFile"
	Gateway_CreateFile_FullMethodName        = "/gateway.v1.Gateway/CreateFile"
	Gateway_CreateFolder_FullMethodName      = "/gateway.v1.Gateway/CreateFolder"
	Gateway_RenameFile_FullMethodName        = "/gateway.v1.Gateway/RenameFile"
	Gateway_MoveFile_FullMethodName          = "/gateway.v1.Gateway/MoveFile"
	Gateway_DeletePath_FullMethodName        = "/gateway.v1.Gateway/DeletePath"
	Gateway_ResolveImport_FullMethodName     = "/gateway.v1.Gateway/ResolveImport"
	Gateway_HomeDir_FullMethodName           = "/gateway.v1.Gateway/HomeDir"
	Gateway_ListDir_FullMethodName           = "/gateway.v1.Gateway/ListDir"
	Gateway_FindProjects_FullMethodName      = "/gateway.v1.Gateway/FindProjects"
	Gateway_DetectConventions_FullMethodName = "/gateway.v1.Gateway/DetectConventions"
	Gateway_AiAgent_FullMethodName           = "/gateway.v1.Gateway/AiAgent"
	Gateway_SaveGraphState_FullMethodName    = "/gateway.v1.Gateway/SaveGraphState"
	Gateway_GetGraphState_FullMethodName     = "/gateway.v1.Gateway/GetGraphState"
)

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gateway to BFF dla aplikacji Electron: proxuje skanowanie do serwisu scanner
// i serwuje graf zależności z bazy. API jest celowo proste i samodzielne
// (bez importów), by Electron ładował je przez @grpc/proto-loader.
type GatewayClient interface {
	// Scan uruchamia skan wierzchni (proxy do scannera) i strumieniuje postęp.
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	// GetGraph zwraca graf projektu: dla monorepo — serwisy (aplikacje) jako węzły,
	// dla pojedynczej app — jej encje. (0 = ostatni przeskanowany).
	GetGraph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*Graph, error)
	// ScanApp robi głęboki skan jednej aplikacji (po app_id) i strumieniuje postęp.
	ScanApp(ctx context.Context, in *ScanAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	// GetAppGraph zwraca wewnętrzny graf jednej aplikacji (klasy/kontrolery/serwisy).
	GetAppGraph(ctx context.Context, in *AppGraphRequest, opts ...grpc.CallOption) (*Graph, error)
	// ListProjects zwraca przeskanowane projekty.
	ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Projects, error)
	// AiEdit zmienia kod wg polecenia (proxy do serwisu ai → LLM).
	AiEdit(ctx context.Context, in *AiEditRequest, opts ...grpc.CallOption) (*AiEditResponse, error)
	// AiModel zwraca nazwę aktualnie używanego modelu (proxy do ai).
	AiModel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AiModelResponse, error)
	// AiSetProvider przełącza dostawcę LLM w serwisie ai (proxy).
	AiSetProvider(ctx context.Context, in *AiProviderRequest, opts ...grpc.CallOption) (*AiModelResponse, error)
	// AiReview zwraca uwagi recenzenta do kodu (per linia) — proxy do ai.
	AiReview(ctx context.Context, in *AiReviewRequest, opts ...grpc.CallOption) (*AiReviewResponse, error)
	// AiComplete zwraca podpowiedź autouzupełniania (Copilot) w miejscu kursora.
	AiComplete(ctx context.Context, in *AiCompleteRequest, opts ...grpc.CallOption) (*AiCompleteResponse, error)
	// PublishEvent / ListEvents — eventy powiązane z plikiem/nodem (proxy do events).
	PublishEvent(ctx context.Context, in *EventInput, opts ...grpc.CallOption) (*Event, error)
	ListEvents(ctx context.Context, in *EventQuery, opts ...grpc.CallOption) (*EventList, error)
	// --- Operacje na plikach (wykonywane PRZEZ gateway; Electron nie rusza fs) ---
	ReadFile(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FileContent, error)
	SaveFile(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*FileResult, error)
	CreateFile(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*FileResult, error)
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*FileResult, error)
	RenameFile(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*FileResult, error)
	MoveFile(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*FileResult, error)
	DeletePath(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FileResult, error)
	ResolveImport(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*FileResult, error)
	// Przeglądanie dysku i szukanie projektów (przez filer; działa też w Dockerze).
	HomeDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FileResult, error)
	ListDir(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*DirListing, error)
	FindProjects(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FoundProjects, error)
	// Wykrycie konwencji nazw plików i rozszerzenia katalogu (przez filer).
	DetectConventions(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*Conventions, error)
	// AiAgent: ai planuje operacje na plikach/folderach (JSON), gateway je WYKONUJE.
	AiAgent(ctx context.Context, in *AiAgentRequest, opts ...grpc.CallOption) (*AiAgentResponse, error)
	// Graph state (viewport/layout) persisted in Postgres by the designer.
	SaveGraphState(ctx context.Context, in *GraphStateRequest, opts ...grpc.CallOption) (*FileResult, error)
	GetGraphState(ctx context.Context, in *GraphStateKey, opts ...grpc.CallOption) (*GraphStateResponse, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[0], Gateway_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gateway_ScanClient = grpc.ServerStreamingClient[Progress]

func (c *gatewayClient) GetGraph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, Gateway_GetGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ScanApp(ctx context.Context, in *ScanAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[1], Gateway_ScanApp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanAppRequest, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gateway_ScanAppClient = grpc.ServerStreamingClient[Progress]

func (c *gatewayClient) GetAppGraph(ctx context.Context, in *AppGraphRequest, opts ...grpc.CallOption) (*Graph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Graph)
	err := c.cc.Invoke(ctx, Gateway_GetAppGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Projects, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Projects)
	err := c.cc.Invoke(ctx, Gateway_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiEdit(ctx context.Context, in *AiEditRequest, opts ...grpc.CallOption) (*AiEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiEditResponse)
	err := c.cc.Invoke(ctx, Gateway_AiEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiModel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AiModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiModelResponse)
	err := c.cc.Invoke(ctx, Gateway_AiModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiSetProvider(ctx context.Context, in *AiProviderRequest, opts ...grpc.CallOption) (*AiModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiModelResponse)
	err := c.cc.Invoke(ctx, Gateway_AiSetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiReview(ctx context.Context, in *AiReviewRequest, opts ...grpc.CallOption) (*AiReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiReviewResponse)
	err := c.cc.Invoke(ctx, Gateway_AiReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiComplete(ctx context.Context, in *AiCompleteRequest, opts ...grpc.CallOption) (*AiCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiCompleteResponse)
	err := c.cc.Invoke(ctx, Gateway_AiComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PublishEvent(ctx context.Context, in *EventInput, opts ...grpc.CallOption) (*Event, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Event)
	err := c.cc.Invoke(ctx, Gateway_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ListEvents(ctx context.Context, in *EventQuery, opts ...grpc.CallOption) (*EventList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventList)
	err := c.cc.Invoke(ctx, Gateway_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ReadFile(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FileContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileContent)
	err := c.cc.Invoke(ctx, Gateway_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) SaveFile(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_SaveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateFile(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) RenameFile(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) MoveFile(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DeletePath(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_DeletePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ResolveImport(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_ResolveImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) HomeDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_HomeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ListDir(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*DirListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirListing)
	err := c.cc.Invoke(ctx, Gateway_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) FindProjects(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*FoundProjects, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoundProjects)
	err := c.cc.Invoke(ctx, Gateway_FindProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DetectConventions(ctx context.Context, in *FilePath, opts ...grpc.CallOption) (*Conventions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conventions)
	err := c.cc.Invoke(ctx, Gateway_DetectConventions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AiAgent(ctx context.Context, in *AiAgentRequest, opts ...grpc.CallOption) (*AiAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiAgentResponse)
	err := c.cc.Invoke(ctx, Gateway_AiAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) SaveGraphState(ctx context.Context, in *GraphStateRequest, opts ...grpc.CallOption) (*FileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResult)
	err := c.cc.Invoke(ctx, Gateway_SaveGraphState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetGraphState(ctx context.Context, in *GraphStateKey, opts ...grpc.CallOption) (*GraphStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphStateResponse)
	err := c.cc.Invoke(ctx, Gateway_GetGraphState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility.
//
// Gateway to BFF dla aplikacji Electron: proxuje skanowanie do serwisu scanner
// i serwuje graf zależności z bazy. API jest celowo proste i samodzielne
// (bez importów), by Electron ładował je przez @grpc/proto-loader.
type GatewayServer interface {
	// Scan uruchamia skan wierzchni (proxy do scannera) i strumieniuje postęp.
	Scan(*ScanRequest, grpc.ServerStreamingServer[Progress]) error
	// GetGraph zwraca graf projektu: dla monorepo — serwisy (aplikacje) jako węzły,
	// dla pojedynczej app — jej encje. (0 = ostatni przeskanowany).
	GetGraph(context.Context, *GraphRequest) (*Graph, error)
	// ScanApp robi głęboki skan jednej aplikacji (po app_id) i strumieniuje postęp.
	ScanApp(*ScanAppRequest, grpc.ServerStreamingServer[Progress]) error
	// GetAppGraph zwraca wewnętrzny graf jednej aplikacji (klasy/kontrolery/serwisy).
	GetAppGraph(context.Context, *AppGraphRequest) (*Graph, error)
	// ListProjects zwraca przeskanowane projekty.
	ListProjects(context.Context, *Empty) (*Projects, error)
	// AiEdit zmienia kod wg polecenia (proxy do serwisu ai → LLM).
	AiEdit(context.Context, *AiEditRequest) (*AiEditResponse, error)
	// AiModel zwraca nazwę aktualnie używanego modelu (proxy do ai).
	AiModel(context.Context, *Empty) (*AiModelResponse, error)
	// AiSetProvider przełącza dostawcę LLM w serwisie ai (proxy).
	AiSetProvider(context.Context, *AiProviderRequest) (*AiModelResponse, error)
	// AiReview zwraca uwagi recenzenta do kodu (per linia) — proxy do ai.
	AiReview(context.Context, *AiReviewRequest) (*AiReviewResponse, error)
	// AiComplete zwraca podpowiedź autouzupełniania (Copilot) w miejscu kursora.
	AiComplete(context.Context, *AiCompleteRequest) (*AiCompleteResponse, error)
	// PublishEvent / ListEvents — eventy powiązane z plikiem/nodem (proxy do events).
	PublishEvent(context.Context, *EventInput) (*Event, error)
	ListEvents(context.Context, *EventQuery) (*EventList, error)
	// --- Operacje na plikach (wykonywane PRZEZ gateway; Electron nie rusza fs) ---
	ReadFile(context.Context, *FilePath) (*FileContent, error)
	SaveFile(context.Context, *SaveRequest) (*FileResult, error)
	CreateFile(context.Context, *CreateRequest) (*FileResult, error)
	CreateFolder(context.Context, *CreateFolderRequest) (*FileResult, error)
	RenameFile(context.Context, *RenameRequest) (*FileResult, error)
	MoveFile(context.Context, *MoveRequest) (*FileResult, error)
	DeletePath(context.Context, *FilePath) (*FileResult, error)
	ResolveImport(context.Context, *ResolveRequest) (*FileResult, error)
	// Przeglądanie dysku i szukanie projektów (przez filer; działa też w Dockerze).
	HomeDir(context.Context, *Empty) (*FileResult, error)
	ListDir(context.Context, *FilePath) (*DirListing, error)
	FindProjects(context.Context, *FilePath) (*FoundProjects, error)
	// Wykrycie konwencji nazw plików i rozszerzenia katalogu (przez filer).
	DetectConventions(context.Context, *FilePath) (*Conventions, error)
	// AiAgent: ai planuje operacje na plikach/folderach (JSON), gateway je WYKONUJE.
	AiAgent(context.Context, *AiAgentRequest) (*AiAgentResponse, error)
	// Graph state (viewport/layout) persisted in Postgres by the designer.
	SaveGraphState(context.Context, *GraphStateRequest) (*FileResult, error)
	GetGraphState(context.Context, *GraphStateKey) (*GraphStateResponse, error)
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServer struct{}

func (UnimplementedGatewayServer) Scan(*ScanRequest, grpc.ServerStreamingServer[Progress]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedGatewayServer) GetGraph(context.Context, *GraphRequest) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGraph not implemented")
}
func (UnimplementedGatewayServer) ScanApp(*ScanAppRequest, grpc.ServerStreamingServer[Progress]) error {
	return status.Error(codes.Unimplemented, "method ScanApp not implemented")
}
func (UnimplementedGatewayServer) GetAppGraph(context.Context, *AppGraphRequest) (*Graph, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppGraph not implemented")
}
func (UnimplementedGatewayServer) ListProjects(context.Context, *Empty) (*Projects, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedGatewayServer) AiEdit(context.Context, *AiEditRequest) (*AiEditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiEdit not implemented")
}
func (UnimplementedGatewayServer) AiModel(context.Context, *Empty) (*AiModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiModel not implemented")
}
func (UnimplementedGatewayServer) AiSetProvider(context.Context, *AiProviderRequest) (*AiModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiSetProvider not implemented")
}
func (UnimplementedGatewayServer) AiReview(context.Context, *AiReviewRequest) (*AiReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiReview not implemented")
}
func (UnimplementedGatewayServer) AiComplete(context.Context, *AiCompleteRequest) (*AiCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiComplete not implemented")
}
func (UnimplementedGatewayServer) PublishEvent(context.Context, *EventInput) (*Event, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedGatewayServer) ListEvents(context.Context, *EventQuery) (*EventList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedGatewayServer) ReadFile(context.Context, *FilePath) (*FileContent, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedGatewayServer) SaveFile(context.Context, *SaveRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedGatewayServer) CreateFile(context.Context, *CreateRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedGatewayServer) CreateFolder(context.Context, *CreateFolderRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedGatewayServer) RenameFile(context.Context, *RenameRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedGatewayServer) MoveFile(context.Context, *MoveRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedGatewayServer) DeletePath(context.Context, *FilePath) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePath not implemented")
}
func (UnimplementedGatewayServer) ResolveImport(context.Context, *ResolveRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveImport not implemented")
}
func (UnimplementedGatewayServer) HomeDir(context.Context, *Empty) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeDir not implemented")
}
func (UnimplementedGatewayServer) ListDir(context.Context, *FilePath) (*DirListing, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedGatewayServer) FindProjects(context.Context, *FilePath) (*FoundProjects, error) {
	return nil, status.Error(codes.Unimplemented, "method FindProjects not implemented")
}
func (UnimplementedGatewayServer) DetectConventions(context.Context, *FilePath) (*Conventions, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectConventions not implemented")
}
func (UnimplementedGatewayServer) AiAgent(context.Context, *AiAgentRequest) (*AiAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AiAgent not implemented")
}
func (UnimplementedGatewayServer) SaveGraphState(context.Context, *GraphStateRequest) (*FileResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveGraphState not implemented")
}
func (UnimplementedGatewayServer) GetGraphState(context.Context, *GraphStateKey) (*GraphStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGraphState not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}
func (UnimplementedGatewayServer) testEmbeddedByValue()                 {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	// If the following call panics, it indicates UnimplementedGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServer).Scan(m, &grpc.GenericServerStream[ScanRequest, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gateway_ScanServer = grpc.ServerStreamingServer[Progress]

func _Gateway_GetGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_GetGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetGraph(ctx, req.(*GraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ScanApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanAppRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServer).ScanApp(m, &grpc.GenericServerStream[ScanAppRequest, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gateway_ScanAppServer = grpc.ServerStreamingServer[Progress]

func _Gateway_GetAppGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetAppGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_GetAppGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetAppGraph(ctx, req.(*AppGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListProjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiEdit(ctx, req.(*AiEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiModel(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiSetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiSetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiSetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiSetProvider(ctx, req.(*AiProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiReview(ctx, req.(*AiReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiComplete(ctx, req.(*AiCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PublishEvent(ctx, req.(*EventInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListEvents(ctx, req.(*EventQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ReadFile(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_SaveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).SaveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_SaveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).SaveFile(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateFile(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).RenameFile(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).MoveFile(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DeletePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DeletePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_DeletePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DeletePath(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ResolveImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ResolveImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_ResolveImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ResolveImport(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_HomeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).HomeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_HomeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).HomeDir(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListDir(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_FindProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).FindProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_FindProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).FindProjects(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DetectConventions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DetectConventions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_DetectConventions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DetectConventions(ctx, req.(*FilePath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AiAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).AiAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_AiAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).AiAgent(ctx, req.(*AiAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_SaveGraphState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).SaveGraphState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_SaveGraphState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).SaveGraphState(ctx, req.(*GraphStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetGraphState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphStateKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetGraphState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_GetGraphState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetGraphState(ctx, req.(*GraphStateKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGraph",
			Handler:    _Gateway_GetGraph_Handler,
		},
		{
			MethodName: "GetAppGraph",
			Handler:    _Gateway_GetAppGraph_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _Gateway_ListProjects_Handler,
		},
		{
			MethodName: "AiEdit",
			Handler:    _Gateway_AiEdit_Handler,
		},
		{
			MethodName: "AiModel",
			Handler:    _Gateway_AiModel_Handler,
		},
		{
			MethodName: "AiSetProvider",
			Handler:    _Gateway_AiSetProvider_Handler,
		},
		{
			MethodName: "AiReview",
			Handler:    _Gateway_AiReview_Handler,
		},
		{
			MethodName: "AiComplete",
			Handler:    _Gateway_AiComplete_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _Gateway_PublishEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _Gateway_ListEvents_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _Gateway_ReadFile_Handler,
		},
		{
			MethodName: "SaveFile",
			Handler:    _Gateway_SaveFile_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _Gateway_CreateFile_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _Gateway_CreateFolder_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _Gateway_RenameFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _Gateway_MoveFile_Handler,
		},
		{
			MethodName: "DeletePath",
			Handler:    _Gateway_DeletePath_Handler,
		},
		{
			MethodName: "ResolveImport",
			Handler:    _Gateway_ResolveImport_Handler,
		},
		{
			MethodName: "HomeDir",
			Handler:    _Gateway_HomeDir_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _Gateway_ListDir_Handler,
		},
		{
			MethodName: "FindProjects",
			Handler:    _Gateway_FindProjects_Handler,
		},
		{
			MethodName: "DetectConventions",
			Handler:    _Gateway_DetectConventions_Handler,
		},
		{
			MethodName: "AiAgent",
			Handler:    _Gateway_AiAgent_Handler,
		},
		{
			MethodName: "SaveGraphState",
			Handler:    _Gateway_SaveGraphState_Handler,
		},
		{
			MethodName: "GetGraphState",
			Handler:    _Gateway_GetGraphState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _Gateway_Scan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ScanApp",
			Handler:       _Gateway_ScanApp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway/v1/gateway.proto",
}
